news/11.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-parsedatetime.py

Fixes [4995](https://github.com/pyinstaller/pyinstaller/issues/4995).
I've not really tested it to death. Anything you'd particularly want it tested for?

Add hook for parsedatetime

---

19.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-workflow.py

add hook for workflow

---

MANIFEST.in
news/33.new.rst
src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_pyproj.py
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyproj.py

Fixes pyinstaller/pyinstaller#4828

Add standard and runtime hook for pyproj

---

news/40.new.rst
requirements-test.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-publicsuffix2.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

And here's the next one! 😃
I will send PRs sequentially, as there's otherwise a merge conflict on each PR.

Add a hook for publicsuffix2

---

news/41.new.rst
requirements-test.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydivert.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

...and a final one. Thanks y'all! :-)

Add a hook for pydivert

---

hook-prettytable.py
news/72.new.rst

Add hook-prettytable.py: pyinstaller not working with prettytable module. 
Fixes https://github.com/pyinstaller/pyinstaller/issues/5319

Add prettytable hook

---

news/87.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-rpy2.py

rpy2 is a library for interfacing with the R programming language https://github.com/rpy2/rpy2/

hooks: add hook for rpy2

---

news/88.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyqtgraph.py

pyqtgraph is a fast plotting library https://pyqtgraph.readthedocs.io/en/latest/

hooks: add hook for pyqtgraph

---

news/100.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-statsmodels.py
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-statsmodels.tsa.statespace.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Based on [this comment](https://github.com/pyinstaller/pyinstaller/issues/3921#issuecomment-516895178)

Add statsmodels hook with hidden imports

---

news/120.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-flirpy.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Added a hook to pull in the necessary data files to use flirpy on a project.

hooks: add hook for flirpy

---

news/122.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-humanize.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Taken from https://github.com/jmoiron/humanize/issues/105#issuecomment-594826403, credits go to @2press. 👍

Add hook for humanize to collect package metadata

---

news/134.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sunpy.py

From the suggestions over at #112 
This hook only contains the files and imports which do not any tests.

Adds hook for sunpy

---

.github/workflows/release.yml

Just a niceity related to #131

Add changelog link to GitHub releases

---

news/280.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_uploader.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Add a hook for `dash-uploader` to collect data files

Add hook-dash_uploader.py

---

news/277.bugfix.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.metrics.cluster.py

Update hiddenimports for sklearn 0.22.

---

news/291.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-rtree.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

https://github.com/pyinstaller/pyinstaller/discussions/6060#discussioncomment-1142925

hooks: add hook for rtree (rokm)

---

README.md

Here is a duplicated description.

Readme: reword installation sentences

---

news/310.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-docx2pdf.py

hooks - Add Hook for docx2pdf

---

news/321.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyvjoy.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Saw this [here](https://stackoverflow.com/questions/69221873/)

hooks: add hook for pyvjoy

---

news/325.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sacremoses.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

One of packages that get in the way due to missing data when people try to package `transformers`...

hooks: add hook for sacremoses

---

CHANGELOG.rst
news/news.300.rst

I didn't notice the naming convention

fix missing changelog

---

README.md

As the title suggests, include a guide for contributing hooks in the README. 
This ended up quite a bit longer than I was expecting - by which I mean that I think it's too long. I'd forgotten just how many hoops we have to jump through.
@colin-fsa As you're the most recent person to ask me the *are any of these steps written down somewhere?* question, I'd appreciate your review on this.

Add a guide to contributing hooks.

---

news/392.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-gitlab.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

https://github.com/albundy83/pyinstaller-hooks-contrib/actions/runs/1913214455

Hook for gitlab

---

news/394.update.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-shapely.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

hook: update shapely hook for compatibility with v.1.8.1

---

news/417.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pypemicro.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Add hook-pypemicro.py

---

news/442.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-limits.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

https://github.com/Sarhamam/pyinstaller-hooks-contrib/actions/runs/2446779431

Add hook for limits

---

news/445.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-great_expectations.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Closes #445. Or at least, fixes the problem of missing data.

hooks: add hook for great_expectations

---

news/483.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-ldfparser.py

Added hook for [ldfparser](https://pypi.org/project/ldfparser/), LIN database parsing library.

Added hook for ldfparser

---

requirements-test.txt

Remove the empty requirements.txt file.

Remove requirements.txt

---

news/521.new.1.rst
news/521.new.2.rst
news/521.new.rst
news/521.update.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cf_units.py
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cftime.py
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-compliance_checker.py
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-netCDF4.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

Add hooks for compliance_checker and its dependencies

---

CHANGELOG.rst
news/524.update.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py

Add dotenv to the list of pydantic hidden imports

---

README.md
hooks-config.rst
news/530.new.rst
news/530.process.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-easyocr.py

I hope what I've done is not too controversial :)

hooks: add hook for easyocr

---

news/534.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-charset_normalizer.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

charset-normalizer has gone down my pet hatred route of squirting random submodules through Cython...
Fixes #534.

Add hidden import for charset-normalizer.

---

news/547.update.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.metrics.py

Update sklearn hooks for compatibility with scikit-learn 1.2.0

---

news/579.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-graphql_query.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

graphql_query needs its templates folder, otherwise the jinja2 loader will fail

Add hook for graphql_query

---

news/581.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pylibmagic.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

This commit adds a hook for the [pylibmagic](https://pypi.org/project/pylibmagic/) package.

Add hook for pylibmagic

---

news/608.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-astropy_iers_data.py

This package includes data which is otherwise missing.

Add hook for astropy-iers-data

---

news/607.new.rst
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skyfield.py

This adds a hook for the skyfield package, which includes data

Add hook for skyfield package

---

news/629.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-simplemma.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

This PR adds a hook for [simplemma](https://github.com/adbar/simplemma), which is a simple multilingual lemmatizer.

hooks: add hook for simplemma

---

news/690.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pygwalker.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

test workflow:
https://github.com/longxiaofei/pyinstaller-hooks-contrib/actions/runs/7556935995

Add hook for pygwalker

---

news/719.new.rst
requirements-test-libraries.txt
src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pptx.py
src/_pyinstaller_hooks_contrib/tests/test_libraries.py

This hook includes the templates required to creating pptx files.

Add hook for python-pptx

---

_pyinstaller_hooks_contrib/stdhooks/hook-itk.py
_pyinstaller_hooks_contrib/stdhooks/hook-monai.py
news/778.new.1.rst
news/778.new.rst
tests/test_deep_learning.py
tests/test_libraries.py

Closes #777
I manually tested import functionality. No tests written due to https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/777#issuecomment-2271762737

Add hooks for ITK and MONAI

---

_pyinstaller_hooks_contrib/stdhooks/hook-capstone.py
news/787.new.rst
requirements-test-libraries.txt
tests/test_libraries.py

Add hook for `capstone` to collect needed libs

Add hook for capstone

---

_pyinstaller_hooks_contrib/stdhooks/hook-sv_ttk.py
news/823.new.rst
news/826.new.rst
requirements-test-libraries.txt
tests/test_libraries.py

This hook ensures that tcl files are collected during the building process.

Add hook for sv_ttk

---

.github/PULL_REQUEST_TEMPLATE.md
news/README.txt

Hopefully this will save us a few *please add test+news entry* comments...

 Link to pull request checklist in pull request template

---

_pyinstaller_hooks_contrib/stdhooks/hook-niquests.py
news/888.new.rst
requirements-test-libraries.txt
tests/test_libraries.py

I am the maintainer of Niquests.
There was one demand of a particular user that prompted me to write that hook.
related to https://github.com/jawah/niquests/issues/225

hooks: add hook for niquests

---

_pyinstaller_hooks_contrib/stdhooks/hook-usb.py
news/906.update.rst

hooks: usb: fix binary collect on windows
