pyinstaller/pyinstaller-hooks-contrib

- news/6.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-eel.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Hi! I hope this is the correct place to put up a contribution and the right way to do it.
I'm maintaining a project called [Eel](https://github.com/samuelhwilliams/Eel) which currently has a [custom build script](https://github.com/samuelhwilliams/Eel/blob/master/eel/__main__.py) to help pull in the correct files. It would be nice if that was less necessary by having a pyinstaller hook for it.
Please let me know if anything more is needed.
> Add hook for eel to collect eel.js and an import

- news/12.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dask.py
Fixes [4984](https://github.com/pyinstaller/pyinstaller/issues/4984) as scikit-image uses dask in Anaconda.
> Add hook for dask

- news/13.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cv2.py
Failing to bundle this DLL may result in different behavior between original and distributed version when dealing with video files.
PyPI version seems to install the DLL into site-packages\cv2, while Conda installs it into prefix\Library\bin.
> hooks: cv2: try to bundle opencv_videio_ffmpeg*.dll on  Windows

- README.md
The instructions for adding to the changelog aren't visible enough. Hopefully this will help avoid having to re-explaining this in every new PR.
I meant to push this to my fork then PR but forgot to `git remote set-url`.  I'll try to fork in future.
Also the white-space changes weren't intentional. I can revert them if you want.
> Add link to news/README.md to the main README.md.

- news/16.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tinycss2.py
Adds a hook for tinycss2. Credit goes to @Legorooj for your answer on StackOverflow: https://stackoverflow.com/questions/61467195/filenotfounderror-errno-2-no-such-file-or-directory-tinycss2-version
> Add hook for tinycss2 for missing data files

- news/21.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-gmplot.py
Due to the issue faced by users of gmplot with conversion to .exe using PyInstaller, this hook was created to include data files along with gmplot. Fixes #20.
> Add gmplot hook

- news/23.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-apscheduler.py
APScheduler relies on entry points to find and dynamically import executors, job stores and triggers.
> Add hook for APScheduler.

- CHANGELOG.rst
- news/26.new.rst
- requirements-test.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-iminuit.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
iminuit uses a cython module which imports sub-modules. These are not normally detected by pyinstaller. This hook uses collect_submodules to add the missing modules as hidden imports, excluding tests.
> Add iminuit hooks

- MANIFEST.in
Fixes #31 - i.e. we forgot to add the licenses to the `MANIFEST.in` so that they are included in `sdist`s. @Legorooj Can you confirm if both the `LICENSE` and `LICENSE.APL.txt` should be included or just the former? And does this warrant a changelog entry?
> Add missing licences to MANIFEST.in

- news/48.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-flask_restx.py
**Problem**:
After packaging a flask app that utilizes [`flask_restx`](https://flask-restx.readthedocs.io)  extension, I'm getting an error that indicates the package template files are missing.
**Solution**:
- Add a file hook to include the extension template files.
- Add a reference to the news changelog.
**Related Issues**:
Fixes #47
> Add hook for flask_restx

- news/50.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tensorflow.py
This is a follow-up to the previous `tensorflow` hook cleanup:
* fix #49 by explicitly excluding `tensorflow.python._pywrap_tensorflow_internal`. 
* avoid packaging tensorflow's development headers, XLA AOT runtime sources, and duplicating the `libtensorflow_framework` shared library (the unused copy picked up via `datas` ends up in `tensorflow` folder, while the one picked up by dependency analysis ends up in program root)
> Fix library duplication in tensorflow v.2.3 and avoid packaging unnecessary files

- news/52.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.feature.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.graph.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a basic import test for `skimage` based on the issues encountered while solving pyinstaller/pyinstaller#5197. 
Based on the test failures under scikit-image 0.17.2, we need additional hooks for `skimage.feature` and `skimage.graph` to deal with the missing (sub)modules.
> Add hooks for skimage.feature and skimage.graph

- news/54.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tinycss2.py
tinycss2 https://github.com/Kozea/tinycss2/pull/27 updated the packaging which removes the need for a hook.
> Exclude tinycss2 hook for versions after 1.0.0

- news/55.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tensorflow.py
The import libraries should not be required at the runtime, and they drive up the resulting program size.
See discussion at pyinstaller/pyinstaller#5236.
> hooks: tensorflow: avoid collecting import libraries on Windows

- news/56.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-markdown.py
Markdown 3.3 introduces a new htmlparser submodule with hidden dependency on html.parser.
> hooks: compatibility fix for markdown 3.3

- news/58.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-win32ctypes.core.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
We need a hook to collect all submodules from `win32ctypes.core.cffi` or `win32ctypes.core.ctypes` (depending on availability of `cffi`) to avoid missing module errors when using `win32ctypes` pywin32 compatibility layer.
> hooks: add a hook for win32ctypes.core

- news/59.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-zmq.py
This PR aims to work around the `UnicodeDecodeError` issue from pyinstaller/pyinstaller#2258. Trying to collect all submodules of `zmq.backend` triggers compilation of C extension for the `cffi` backend (provided cffi and C compiler are installed), but individually collecting each backend submodule does not, which means no potentially breaking error messages from MSC on Windows.
After some more investigation, it turned out that cffi backend requires collection of data files; otherwise lack thereof triggers a file-not-found error when trying to import the backend module.
But even with that, the `cffi` backend does not seem to be usable in a frozen program, as its import fails with `Failed to import zm.backend.cffi: PyZMQ CFFI backend couldn't find zeromq: invalid command 'build`. The error …
> hooks: zmq: avoid triggering compilation of C extension for cffi backend

- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
New pytest markers were introduced in https://github.com/pyinstaller/pyinstaller/pull/5291:
- `@pytest.mark.darwin` (only runs on macOS)
- `@pytest.mark.linux` (only runs on GNU/Linux)
- `@pytest.mark.win32` (only runs  on Windows)
> Backport changes from pyinstaller/pyinstaller#5291

- news/64.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-ijson.py
Hook for the ijson package at: https://github.com/ICRAR/ijson
Ijson is an iterative JSON parser which is useful for reading very large json files. The backend modules necessary to run ijson are dynamically loaded hence the need for this hook.
> hooks: Add hook for ijson

- news/66.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-lxml.py
lxml has hiddenimports and is not fully embedded when adding it to hiddenimports
`hiddenimports = ['lxml'] `is not enough
see https://github.com/pyinstaller/pyinstaller/issues/5306
> hooks: Add hook for lxml

- news/67.update.rst
- src/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py
Use a custom `exec_statement()` to query the `win32com.__file__` instead of using `get_module_file_attribute()`, as the latter
will print a `ModuleNotFindError` to stderr when the module is unavailable. The error message, while harmless, appears
to be bothering the users.
Fixes pyinstaller/pyinstaller#3733.
> hooks: win32com: avoid printing ModuleNotFindError when module is unavailable

- news/68.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-gcloud.py
Add hook-cloud.py: pyinstaller not working with pyrebase google module.
Fixes [#5316](https://github.com/pyinstaller/pyinstaller/issues/5316).
> Add hook-gcloud.py

- news/69.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-afmformats.py
afmformats is a library for opening common atomic force microscopy (AFM) data files.
https://afmformats.readthedocs.io
> hooks: Add hook for afmformats.

- news/70.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyproj.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
On versions prior to 2.3.0, we require a hidden import of `pyproj._datadir`.
On versions 3.0.0 or newer, we require a hidden import of `pyproj._compat`, and on linux/macOS also `distutils.util`.
This allows the test to pass under wide range of pyproj versions, from 2.1.3 to 3.0.0.
> hooks: update pyproj hook to improve compatibility across different versions

- news/71.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sentry_sdk.py
Sentry added in PR getsentry/sentry-python#625 by default enabled integrations. We need to add them to the hidden imports to be able to launch a application with sentry.
I added the hasattr check for backwards compatibility
> Add default enabled sentry integrations dynamically to hidden imports

- news/78.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
The PyPi version of `pydantic` comes with all its modules compiled as cpython extensions. This prevents `pyinstaller` from properly discovering the dependant modules, both from the `pydantic` package itself and from the standard library.
Fixes pyinstaller/pyinstaller#5359.
> Add hook for pydantic

- pytest.ini
In order to avoid `PytestUnknownMarkWarning` warnings.
> tests: define the darwin/linux/win32 pytest markers

- news/80.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torchvision.ops.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add a hidden import of `torchvision._C` extension module that we fail to pick up automatically. This extension module is required in functions from `torchvision.ops.*` modules, where its absence causes the `_assert_has_ops()` call to fail.
Fixes pyinstaller/pyinstaller#5386
> Add a hook for torchvision.ops

- news/82.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-googleapiclient.model.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
The `googleapiclient.model` module uses `pkg_resources` and its `get_distribution()` function to query the version of `google-api-python-client` package, therefore we need to collect its metadata.
Fixes pyinstaller/pyinstaller#5332.
Fixes #14.
> hooks: add hook for googleapiclient.model

- news/81.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py
Addendum to previous attempt at the `pydantic` hook (#78).
As established in pyinstaller/pyinstaller#5432, the `dataclasses` module from standard library also needs to be added to `hiddenimports`. In older versions of compiled `pydantic`, this missing module would cause an error when importing `pydantic` itself (https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/78#issuecomment-739382401), while in newer ones the import is done within the functions and so the error is deferred until the function call.
Therefore, this partially addresses [the failing linux test from the previous one-shot test](https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/402946595). Afterwards, another issue crops up; versions of `pydantic` prior to 1.4 use `distutils.version` in …
> hooks: pydantic: add missing dataclasses and distutils.version hidden imports

- news/83.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pdfminer.py
Pdfminer.six library was not extracting some Japanese texts from a
PDF file after being bundled with Pyinstaller.
Fixes #5509
> Added hook for pdfminer.six library.

- news/86.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pygraphviz.py
pygraphviz assumes a working graphviz installation.
https://graphviz.org/download/ recommends `brew install graphviz` on
macOS and `choco install graphviz` on Windows, so look for the graphviz
binaries / configs where those tools install by default.
> Add hook for the pygraphviz library

- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pygraphviz.py
Instead of a brute-force glob. This paves the way to get the hook
working on Linux as well, where bundling /usr/bin/* is obviously a
no-go.
See
<https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/86#issuecomment-774312818>
for more details.
> pygraphviz hook: check for executables based on a list

- .github/workflows/macos-test.yml
Also, disable `fast-fail` so we can get the full picture about failing tests.
> macOS CI: replace python 3.5 with 3.9

- news/90.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py
Pydantic 1.8.0 introduced additional dependency on `typing_extensions` module, which needs to be added to `hiddenimports` for the compiled version of pydantic.
Fixes pyinstaller/pyinstaller#5603.
> hooks: update pydantic hook for compatibility with v.1.8.0 and later

- .travis.yml
- appveyor.yml
Missed these two in the previous PR...
> CI: replace python 3.5 with 3.9 on AppVeyor and Travis

- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pygraphviz.py
See
<https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/86#pullrequestreview-584684190>,
this was not done before due to an implicit list of executables, which
is no longer a problem.
Keep the logic as "if windows, else if macos, else", so it can cover not
only Linux, but other similar cases (BSD, etc).
> pygraphviz hook: add Linux support

- news/98.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-zmq.py
Windows wheel of `pyzmq` 22.0.0 introduced separate shared library directory in `site-packages/pyzmq.libs` which is dynamically added to the path and hence eludes our binary analysis.
There's also a `.load_order` file in there that needs to be collected for python versions older than 3.8 (and is also needed on newer
versions to ensure that `pyzmq.libs` directory is created).
> hooks: update zmq hook for compatibility with version 22.0.0+ on Windows

- news/97.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-googleapiclient.model.py
Implements the fix commented [here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/82#issuecomment-796438598) on #82.
TL;DR: Using google-api-python-client for Blogger API causes `build()` method to raise error and None value due to missing `googleapiclient.discovery` files.
> Added googleapiclient.discovery

- .github/workflows/oneshot-test.yml
- news/101.new.rst
- scripts/cloud-test.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyttsx3.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `pyttxs3`. Fixes pyinstaller/pyinstaller#3268 and a rather long [nabble thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pyinstaller/IJXFdvIs--0/D85e6cD7AQAJ).
We do have a hook and test already for `pyttxs` (without the `3`) which is handled similarly but I'd prefer to keep them separate.
There's also a couple of extra commits tucked under here which I can't be bothered to separate into their own PRs. I'll merge this manually to keep the git history.
- 112f500 CI/CD: Oneshot: Allow custom bash install commands. This is so I can run any `sudo apt install [dependencies]` when needed.
- a7fedf0 CI/CD: Oneshot: Remove Python 3.5, add 3.9.
I've done oneshot testing in bits:
- [scripts/cloud-test.py --os=windows --os=macos pyttsx3==2.90, …
> Add hook for pyttsx3.

- .github/workflows/macos-test.yml
- news/103.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_bootstrap_components.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_core_components.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_html_components.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_renderer.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dash_table.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-flask_compress.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-plotly.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Fixes #102
So I started with `dash_html_components` which was my initial use case, but since getting positive feedback, I did some additional research to see what users were struggling with ([here](https://stackoverflow.com/questions/59914106/pyinstaller-error-when-executing-plotly-dash-exec-file), [here](https://stackoverflow.com/questions/60049673/how-to-pack-a-plotly-dash-application-with-pyinstaller-into-a-single-exe-file-fo), etc.). I also did a deeper dive using a standalone project to test out the hooks and make sure they covered the most common use cases: https://github.com/KyleKing/Poetry-EdgeCaseTesting
There is also an issue with `dash` which calls `pkg_resources.get_distribution` on `flask-compress` so there needs be a `copy_metadata` in the flask compress hook
I would be …
> Add hooks for dash and related packages (#102)

- news/107.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.filters.py
Add missing `skimage.filters.rank.core_cy_3d` hidden import.
Fixes pyinstaller/pyinstaller#5721.
> hooks: update scikit-image hooks for compatibility with 0.18.x series

- news/108.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.linear_model.py
Add missing `sklearn.utils._weight_vector` hidden import.
> hooks: update scikit-learn hooks for compatibility with 0.24.x series

- news/113.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pycountry.py
Based off this thread: http://pyinstaller.47505.x6.nabble.com/PyInstaller-not-working-with-module-pycountry-td3064.html
I faced this same issue, used this modified hook, and it worked.
> Add copy_metadata to pycountry hook

- news/114.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pypylon.py
Closes https://github.com/basler/pypylon/issues/118
Probably abuses pyinstaller hooks a bit, but the way pypylon handles its libraries makes it really difficult for an automated tool to perform packaging.
Tested with Linux and Windows.
> Add hook for pypylon

- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-IPython.py
> hooks: IPython: remove use of compat.modname_tkinter

- news/116.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pypylon.py
#114 missed the data files required for discovering cameras.
Tested to work on a new Windows installation.
> Update hook for pypylon to include data files

- news/119.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-blspy.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Collects `MPIR` backend DLLs on Windows.
Fixes #118.
> hooks: add hook for blspy

- news/123.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-azurerm.py
Azurerm is a lite api to microsoft azure.
Azurerm is using pkg_resources internally which is not supported by py-installer.
This hook will collect the module metadata.
Tested with Azurerm 0.10.0
> Create hook for Azurerm which is using pkg_resources internally

- news/126.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-jsonrpcserver.py
Add a simple hook to include missing [request-schema.json](https://github.com/bcb/jsonrpcserver/blob/master/jsonrpcserver/request-schema.json) file required by [jsonrpcserver](https://github.com/bcb/jsonrpcserver) python package.
> hooks: add hook for jsonrpcserver

- LICENSE.APL.txt
- LICENSE.GPL.txt
- news/128.1.new.rst
- news/128.2.new.rst
- news/128.3.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-spacy.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-srsly.msgpack._packer.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-thinc.backends.numpy_ops.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-thinc.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
The [issue](https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/38) refers to preshed, but it seems like spacy is actually the root of the problem. I also reviewed [pyinstaller/pyinstaller#4696](https://github.com/pyinstaller/pyinstaller/issues/4696), [pyinstaller/pyinstaller#4053](https://github.com/pyinstaller/pyinstaller/issues/4053), and https://stackoverflow.com/questions/59645155/spacy-2-2-3-filenotfounderror-errno-2-no-such-file-or-directory-thinc-neur. Oddly enough I could find no code to use for testing in any of those places so the test case is just an import. If anybody knows these packages and can suggest a better test case please let me know.
I'm not familiar with any of these packages so I did a trial-and-error approach to figure out the minimum necessary logic …
> Add hooks to get spacy working

- news/138.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-shotgun_api3.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This is a hook for the [Shotgrid python API](https://github.com/shotgunsoftware/python-api).
Let me know if there is something missing/wrong with this PR! 🙂
> Add hook for "shotgun_api3"

- news/139.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-msoffcrypto.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
I'm having trouble figuring out how to handle this one and was hoping I could get some advice. The offending line from the package seems to be `__version__ = pkg_resources.get_distribution("msoffcrypto-tool").version`. The version was a hardcoded string in the prior release and everything worked fine then, here's the commit that broke it: https://github.com/nolze/msoffcrypto-tool/commit/161b182a029ced7597c2c5240ed8348467ffeeb9#diff-589d1c7aac0cfc6ed2f443b43655fcaad7fee63a261631470e74e01de91d2e24
My draft hook doesn't help at all, I just left it in the draft PR to show that I had already tried the kitchen sink approach.
> Msoffcrypto

- .github/workflows/oneshot-test.yml
When given a requirement like `humanize>3` bash will interpret the `>` as the *stream to file* operator so that `pip install humanize>3` will really run `pip install humanize` and pipe the output to a file called `3`. Wrapping with quotes (`pip install "humanize>3"`) fixes this but it complicates the CI launching UI because, unless you know why the quotes are needed, you're guessing where/when to use them (see [here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/130#discussion_r654872063) for an example).
Now each requirement given is internally quoted automatically so that there is never any need to manually quote parameters. Input syntax now mostly mirrors that of PEP 508 requirements files with the differences
being that `,` splits jobs and therefore can't be used …
> CI/CD: Oneshot: Implicitly wrap each requirement in double quotes.

- news/275.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-parso.py
Parso uses grammar files for the different python versions.
Ipython uses the parso package for autocomplete.
> hooks: added hook for parso package to get grammar data.

- news/276.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.filters.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.cluster.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.linear_model.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.neighbors.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Use distribution names (`scikit_image` and `scikit_learn`) for version checks via `is_module_satisfies()` instead of package names (`skimage` and `sklearn`). It is possible to install latest `scikit-learn` by installing 'sklearn', which installs `sklearn==0.0` that ends up messing up the version checks.
Make same adjustment in `scikit-image` hooks for the sake of consistency (although trying to install `skimage` shows an error     telling user to install `scikit-image` instead).
> hooks: scikit-image & scikit-learn: use distribution names for version checks

- news/281.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cloudscraper.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add a hook for `cloudscraper` to collect data files.
Data is located at [cloudscraper\user_agent\browsers.json](https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json).
[ci](https://github.com/eric15342335/pyinstaller-hooks-contrib/actions/runs/1084697166)
> Add hook-cloudscraper.py

- news/284.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-mnemonic.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This pull request adds a hook for mnemonic.
See: https://stackoverflow.com/questions/68624566/.
The (text) files which mnemonic needed are located [here.](https://github.com/trezor/python-mnemonic/tree/master/src/mnemonic/wordlist)
> hooks: add hook for mnemonic

- news/288.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pystray.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Pystray [chooses](https://github.com/moses-palmer/pystray/blob/master/lib/pystray/__init__.py#L22) different backends for different platforms. Note that if [this branch](https://github.com/moses-palmer/pystray/tree/feature-explicit-backends) get merged then we don't need this.
(This is the same)
[**CI**](https://github.com/eric15342335/pyinstaller-hooks-contrib/actions/runs/1107971245)
> hooks: add hook for pystray

- news/285.new.rst
- news/296.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-langdetect.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-swagger_spec_validator.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
#285 and #296
I seems can not run the workflow
> hooks: add hook for langdetect and swagger_spec_validator

- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py
In the upcoming PyInstaller 5.x series, the `get_module_attribute()` function will return the actual value instead of its string representation. So compare the returned value for the `compiled` attribute against both `'True'` and `True` for compatibility with both PyInstaller 4.x and 5.x series.
> hooks: future-proof the pydantic hook

- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-platformdirs.py
Only import the platformdirs submodule for the platform the binary is
being built against.
> Per-platform imports for platformdirs

- news/316.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tableauhyperapi.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
<details>
<summary>
wheel
</summary>
```
tableauhyperapi
│   catalog.py
│   connection.py
│   databasename.py
│   date.py
│   endpoint.py
│   hyperexception.py
│   hyperprocess.py
│   hyperserviceversion.py
│   inserter.py
│   interval.py
│   name.py
│   result.py
│   resultschema.py
│   schemaname.py
│   sql.py
│   sqltype.py
│   tabledefinition.py
│   tablename.py
│   timestamp.py
│   warning.py
│   __init__.py
│
├───bin
│   │   tableauhyperapi.dll
│   │
│   └───hyper
│           crashdumper.exe
│           hyperd.exe
│
└───impl
cdef.py
cdef_compiled.py
converter.py
dll.py
dllutil.py
hapi.py
immutablelistwrapper.py
lib_h.py
schemaconverter.py
util.py
version.py
__init__.py
```
</details>
https://stackoverflow.com/questions/69041243/few-packages-in-pyinstaller-is-not-packaged
> hooks: add hook for tableauhyperapi

- news/62.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-folium.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Partially fixes pyinstaller/pyinstaller#5256 and pyinstaller/pyinstaller#5262 (missing data files for `folium`). Full fix requires pyinstaller/pyinstaller#5284 and #61, which are also required for the added test to pass.
> hooks: add hook for folium

- news/60.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-metpy.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Partially fixes pyinstaller/pyinstaller#5247 (missing metadata and data files). Full fix requires pyinstaller/pyinstaller#5284, which is also required for the added test to pass.
>  hooks: add hook for metpy 

- .github/workflows/scheduled-test.yml
- requirements-test-libraries.txt
An attempt at fixing [yesterday's failed scheduled test](https://github.com/pyinstaller/pyinstaller-hooks-contrib/runs/3570109442?check_suite_focus=true).
Python 3.6 pipelines are failing due to latest version of MetPy having dropped support for 3.6.
`qtmodern` tests are failing on linux due to missing system dependencies of `PyQt5`.
> Fix scheduled-test CI

- news/323.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-adbutils.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
adbutils bundles [adb binaries](https://github.com/openatx/adbutils/tree/master/adbutils/binaries) for windows/macos as the fallback adb:
https://github.com/openatx/adbutils/blob/dccec86376ab3fd741cfedb62c0c9b71a58b4877/adbutils/_utils.py#L29-L41
[CI](https://github.com/eric15342335/pyinstaller-hooks-contrib/actions/runs/1265028870)
> hooks: add hook for adbutils

- news/324.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pymediainfo.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Collects bundled `MediaInfo` shared library that is available in macOS and Windows wheels. On other OSes, it attempts to collect
the system-installed `MediaInfo` shared library.
The tests are currently enabled only for macOS and Windows, where we want to check if bundled shared library is properly collected. If we wanted the test to run on Linux, we'd need to install `libmediainfo0v5` via `apt`, but that would be self-defeating, because once system copy is available, the frozen test would pass if the library was collected or not.
> hooks: add hook for pymediainfo

- news/338.new.0.rst
- news/338.new.1.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-panel.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyviz_comms.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
[Panel](https://panel.holoviz.org/) and its dependency `pyviz_comms` needs some data and hidden imports to work. This PR adds hooks for handling this.
> Add hooks for panel and pyviz_comms

- news/348.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-ffpyplayer.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
https://stackoverflow.com/questions/69884761/ffpyplayer-importerror-dll-load-failed-while-importing-player-the-specified
See [here](https://github.com/matham/ffpyplayer/blob/ec3af54c9b45828bdf6691b064c6f4f9e46169f5/ffpyplayer/__init__.py#L27-L29)
> Add a hook for ffpyplayer 

- news/357.update.rst
- setup.cfg
- src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_pygraphviz.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add a runtime hook that overrides `pygraphviz.AGraph._which()` method with custom implementation that searches in `sys._MEIPASS` instead of `PATH`. This allows `pygraphviz` to use collected `graphviz` programs without having to have `sys._MEIPASS` prepended to `PATH` (which it usually it not).
Fixes #357.
> Override pygraphviz' search for graphviz programs

- news/371.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tensorflow.py
We need to explicitly collect keras package and its submodules due to lazy mapping of `tensorflow.keras.xyz` -> `keras.xyz`.
Fixes pyinstaller/pyinstaller#6519. Fixes pyinstaller/pyinstaller#6538.
> hooks: update tensorflow hook to support tensorflow 2.6 and later

- news/376.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-py.py
This fixes [the failing pytest-runner test](https://github.com/pyinstaller/pyinstaller-hooks-contrib/actions/runs/1803605477). [CI/CD](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/1808937412)
> Add hook for py to fix frozen pytest runner.

- news/387.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-altair.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Added a hook for altair that collects some required JSON schema files. Successful test: https://github.com/cascade256/pyinstaller-hooks-contrib/actions/runs/1885014947
By the way, really helpful instructions for contributing!
> Add a hook for altair

- .github/workflows/oneshot-test.yml
- .github/workflows/pyup-test.yml
Multi-command run statements on Windows CI are executed via powershell without any equivalent to bash's `-e` option so that a failed pip install will not set an error exit code for the step and proceed onto running the tests (and most likely passing when it shouldn't).
CI run: https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/2082924736
> CI/CD: Prevent Windows from skipping over a failed pip install.

- news/408.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-av.py
From version 9.1.1 on, Windows PyPI wheels of av use a new DLL directory layout.
> hooks: update av hook for compatibility with >= 9.1.1

- news/406.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-clr_loader.py
`clr_loader` is used by `pythonnet` 3.x, and on Windows, the default runtime (.NET framework) loader requires the package-bundled DLLs to be collected into the frozen application.
See: pyinstaller/pyinstaller#6572, pyinstaller/pyinstaller#6731.
> Add a hook for clr_loader

- news/409.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-lark.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
I came across this issue when using [`commentjson`](https://pypi.org/project/commentjson/). Some Lark `.grammar` files that are needed were not being included when any sort of Lark `%import` was used. This should fix the issue for both the https://pypi.org/project/lark/ and older https://pypi.org/project/lark-parser/ packages (both install to `lark` inside `site-packages`).
Here are the CI results: https://github.com/NathanVaughn/pyinstaller-hooks-contrib/actions/runs/2157919610
Python 3.6 failed as it was unavailable, but I see that that the `setup.cfg` lists `>=3.7`.
I think I got everything, but let me know if I missed something!
> Add hook for lark

- news/412.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-stdnum.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Collect data files required by some of the stdnum's sub-modules.
Closes pyinstaller/pyinstaller#6770.
> Add hook for python-stdnum

- .github/workflows/pr-test.yml
This replaces the trigger for pull requests coming from the PyUp bot and
hopefully will remove the need to manually invoke the oneshot workflow on
incoming pull requests.
> Run CI testing on any pull request touching the requirements file.

- news/420.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-numcodecs.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
numcodecs.compat_ext is only imported from pyx files, so it is missed.
Fixes: zarr-developers/numcodecs#291
> Add hook for numcodecs

- news/426.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-mariadb.py
Always collect the `decimal` module as a hidden import, even if it seems to be automatically picked up on recent python versions.
That likely happens due to import in some other module (e.g., from standard library), but may be subject to change in the future,
so we should not be relying on it. Besides, the hidden import does no harm, even if it is redundant.
> hooks: mariadb: always collect decimal module as hidden import

- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Our adbutils test uses an internal function from `adbutils._utils`. This function was renamed from `get_adb_exe` to `adb_path` in `adbutils` 0.15.0. Update the test accordingly.
> tests: update test_adbutils for compatibility with adbutils >= 0.15.0

- news/432.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sounddevice.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-soundfile.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update hooks for PyInstaller 5.1 compatibility. As `sounddevice` and `soundfile` are not packages but top-level modules, the hookutils `get_package_paths()` now fails due to changes made in PyInstaller 5.1. Both hooks should have been using `get_module_file_attribute()` instead.
Fixes #432.
>  hooks: update sounddevice and soundfile hooks for PyInstaller 5.1

- news/435.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pylint.py
Fix filter function passed to `collect_submodules` to correctly exclude both `pylint.test` sub-package (available in `pylint` <= 2.3) and `pylint.testutils submodule` (`pylint` < 2.7) or subpackage (>= `2.7`).
Previously, `pylint.testutils` and its contents were not excluded.
Closes #435.
> hooks: pylint: fix filter function passed to collect_submodules

- news/438.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-yt_dlp.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for yt_dlp to handle indirect import in yt-dlp v2022.05.18.
Fixes #438.
> hooks: add hook for yt_dlp

- news/451.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-tensorflow.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Register the alias `tensorflow.keras` = `keras.api._v2.keras`, which is required as of `tensorflow >= 2.8.0` for programs that import
only from `tensorflow.keras`.
Add a new import test for `tensorflow.keras` that demonstrates the issue. 
See https://github.com/pyinstaller/pyinstaller/discussions/6890
> hooks: add pre-safe-import hook for tensorflow >= 2.8.0

- news/453.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cv2.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
In linux PyPI `opencv-python` wheels, the `cv2` extension is linked against Qt, and the wheel bundles a basic subset of Qt shared libraries, plugins, and font files. This is not the case on other OSes (presumably native UI APIs are used by the OpenCV HighGUI
module), nor in the headless PyPI wheels (`opencv-python-headless`).
The bundled Qt shared libraries should be picked up automatically due to binary dependency analysis, but we need to collect  plugins and font files from the `qt` subdirectory.
>  hooks: cv2: collect Qt fonts data and plugins from linux PyPI wheels

- news/455.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pandas_flavor.py
Add hook for `pandas_flavor` to handle hidden imports caused by switch to lazy loader in version 0.3.0 of the package.
> hooks: add hook for pandas_flavor

- news/456.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.metrics.pairwise.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.metrics.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sklearn.neighbors.py
A year has gone by, and we have happily forgotten that `scikit-learn` exists. In the meantime, 1.0.x and 1.1.x series have been released, which bring more compiled extensions, and thus more hidden imports that we need to handle.
Fixes #456.
> hooks: update scikit-learn for compatibility with 1.0.x and 1.1.x series

- .github/workflows/pr-test.yml
- news/463.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-mariadb.py
Install MariaDB Connector/C from official MariaDB Community Server repository. The version shipped with Ubuntu 20.04 is too old and is not supported by `mariadb` >= 1.1.3.
> ci: install MariaDB connector from official MariaDB CS repository

- .github/workflows/pr-test.yml
- news/465.bugfix.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyqtgraph.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
In 5.2 the collect_submodules function no longer recurses into
filtered packages (introduced in https://github.com/pyinstaller/pyinstaller/commit/17aa452741f71b9ac4bab0b3cbe566d68a0bdf5f), which broke the pyqtgraph hooks which relied on that behavior.
This fixes the hook by collecting all modules with `collect_submodules`, and filtering
for the hidden modules manually.
Took the opportunity to add tests for `pyqtgraph`.
Fixes #465
> Fix hook-pyqtgraph for PyInstaller 5.2

- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
- install `libxcb-image0` on ubuntu runners to keep PyQt5 happy
- enable colored output, like we do in the main repository
- force bootloader recompilation when installing PyInstaller from `develop` branch
> Couple of CI improvements

- news/468.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cv2.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Collect the `cv2` package contents in pure source mode to bypass the PYZ archive and prevent compatibility issues between PyInstaller's `FrozenImporter` and `cv2` trying to perform module substitution by manipulating `sys.path`. This fixes problems with `opencv-python` and `opencv-python-headless` version 4.5.4.58 and >= 4.6.0.66, but requires PyInstaller with https://github.com/pyinstaller/pyinstaller/pull/6945 merged (i.e., PyInstaller > 5.2). On older PyInstaller versions, this change is no-op and the affected `cv2` versions remain defunct.
Closes pyinstaller/pyinstaller#6889.
Closes pyinstaller/pyinstaller#6964.
This fixes issues with cv2 loader script(s), so it should also fix the problems with loader that comes with OpenCV compiled from source (#110). However, if I recall correctly, …
> hooks: force cv2 collection in source mode

- news/424.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-hydra.py
- src/_pyinstaller_hooks_contrib/tests/data/test_hydra/config.yaml
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
> Add hook for Hydra config system (hydra-core)

- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pypylon.py
The hook was broken in Pyinstaller commit:
https://github.com/pyinstaller/pyinstaller/commit/20f922cdac0207e943395bcae4a23d597558c5f7
Before that, the hook worked "by accident".
> hooks: fix hook-pypylon for PyInstaller 5.1

- news/474.update.rst
- src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_pythoncom.py
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_pywintypes.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pythoncom.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pywintypes.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Have `pywintypes` and `pythoncom` hook collect their corresponding DLLs into `pywin32_system32` sub-directory if the DLLs originally came from `site-packages/pywin32_system32` directory (which is the case with PyPI wheel, but not with Anaconda package). This prevents duplication of `pywintypesXY.dll` when the latter is also collected as a part of link-time binary dependency analysis, which starting with PyInstaller 5.4 attempts to preserve the parent directory structure (https://github.com/pyinstaller/pyinstaller/pull/7028).
> hooks: update pywintypes and pythoncom hooks

- news/477.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyshark.py
Let's put `pyshark` out of its misery...
> Update ``pyshark`` hook to be compatible with versions ``>=0.5``.

- news/400.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-geopandas.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Tested for geopandas 0.10.2 and pyinstaller 4.10
See also these SO questions:
* https://stackoverflow.com/a/51957870
* https://stackoverflow.com/questions/56804095/pyinstaller-stopiteration-error-when-i-import-geopandas
> Add hook for geopandas, which reads data files during import.

- news/486.update.1.rst
- news/486.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-clr.py
Guard against potential sources of errors in the `clr` hook:
- the absence of `pythonnet`, when the hook is triggered by some other module/package named `clr`. (Presumably) fixes https://github.com/pyinstaller/pyinstaller/issues/6283.
- the absence of file list metadata in `pythonnet`. Fixes #485.
> hooks: clr: guard against potential sources of errors

- news/487.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sounddevice.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-soundfile.py
Extend the `sounddevice` and `soundfile` hooks to collect system-installed `sndfile` and `portaudio` shared libraries in cases when the libraries are not bundled with the package (i.e., linux PyPI wheels and Anaconda-provided packages on all OSes).
Fixes the collection part of pyinstaller/pyinstaller#7065.
> hooks: sounddevice and soundfile: collect system-installed shared lib

- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
- .github/workflows/release.yml
- .github/workflows/validate-new-news.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .github/workflows/lint.yml
- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
- .github/workflows/release.yml
- .github/workflows/validate-new-news.yml
Should take care of "Node.js 12 actions are deprecated." warnings in the jobs' summary.
> ci: bump used action versions to ones that use Node 16

- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
- news/500.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-clr.py
- src/_pyinstaller_hooks_contrib/tests/data/netcore5_runtime_config.json
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Instead of trying to load specific .NET runtime via json file, let `clr_loader.get_coreclr()` pick up any installed version it finds.
On CI, install .NET 6.x instead of EOL'd 5.x. Repin pythonnet to 3.0.0.post1, and install it on all OSes, since it should now be fully cross-platform.
> tests: fix the pythonnet3 test

- news/501.update.1.rst
- news/501.update.rst
- src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_pyqtgraph_multiprocess.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyqtgraph.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update `pyqtgraph` standard hook to collect all data from the package, including the colormaps and their associated license files, as per https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/490#issuecomment-1258173167.
Create a new runtime hook that attempts to handle subprocess spawned by `pyqtgraph.multiprocess`. The caveat is that the user still needs to call stdlib `multiprocess.freeze_support` in their entry-point script (which is something I hope to get around to addressing in PyInstaller's `multiprocess` hook). And for onefile builds, they also need to set `_MEIPASS2` environment variable to prevent the executable from unpacking itself again in the subprocess (using different `sys._MEIPASS`, and thus breaking the path check in the runtime hook). This is because …
> Update hooks for pyqtgraph

- .github/workflows/pr-test.yml
- news/506.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-discid.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook and test for [`discid` package](https://pypi.org/project/discid/).
> Add hook for discid package

- news/508.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-exchangelib.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
In some cases `exchengelib` need to collect `tzdata`, I noticed it on `alpine` distribution that it raises this on import
```
exchangelib.errors.UnknownTimeZone: No time zone found with key UTC
```
> Add hook and test for exchnagelib

- news/505.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyproj.py
As of version 3.4.0, pyproj's `__init__.py` queries its own version via `importlib.metadata.version(__package__)`, which requires the package metadata to be collected.
> hooks: pyproj: collect metadata for pyproj >= 3.4.0

- .github/workflows/release.yml
- CHANGELOG.rst
- news/_template.rst
- requirements-release.txt
* Remove heading and top underline from the news template, to avoid duplicates when using latest version of `towncrier` (22.8.0). 
* Pin `towncrier` to 22.8.0 in `requirements-release.txt`.
* Have the Release workflow install dependencies using the `requirements-release.txt`.
* Remove duplicated headings from CHANGELOG.
Closes #513.
> Fix duplicated headers in changelog

- news/536.new.rst
- news/536.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-minecraft_launcher_lib.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This adds a hook for [minecraft-launcher-lib](https://pypi.org/project/minecraft-launcher-lib/)
> Add hook for minecraft-launcher-lib

- news/541.update.1.rst
- news/541.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-fiona.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update `fiona` hook for compatibility with `fiona` 1.9.0 (add `fiona.enums` to hidden imports).
Also ensure that the package's data files are collected, and add a test that shows why they are needed.
> Update fiona hook for compatibility with fiona 1.9.0

- news/545.update.rst
- src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_ffpyplayer.py
Add a run-time hook for `ffpyplayer` that sets site.USER_BASE to an empty string, in order to prevent run-time errors caused by `ffpyplayer` blindly passing `site.USER_BASE` to `os.path.join`.
Due to `site` being disabled in PyInstaller-frozen application, `site.USER_BASE` is `None`. In PyInstaller versions prior to v5.5, this was mitigated by PyInstaller's own fake `site` module, which also set `site.USER_BASE` to an empty string.
> Add work-around for ffpyplayer trying to use site.USER_BASE

- news/546.update.rst
- src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_tensorflow.py
Add a run-time hook for `tensorflow` that sets site.USER_SITE to an empty string, in order to prevent run-time errors caused by `tensorflow` < 2.3.0 blindly passing `site.USER_SITE` to `str.startswith`.
Due to `site` being disabled in PyInstaller-frozen application, `site.USER_SITE` is `None`. In PyInstaller versions prior to v5.5, this was mitigated by PyInstaller's own fake `site` module, which also set `site.USER_SITE` to an empty string.
Fixes #529.
> Add work-around for tensorflow < 2.3.0 trying to use site.USER_SITE

- news/551.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyqtgraph.py
Prevent `pyqtgraph` hook from recursing into `pyqtgraph.examples` while scanning for submodules. While the obtained list of submodules is subsequently filtered to include only templates, import of `pyqtgraph.examples` during scan triggers instantiation of `QtWidgets.QApplication`. This, in turn, requires a valid X/Wayland session on linux and and lack thereof results in an error that crashes the python subprocess in which we scan for submodules.
Fixes the second (linux-specific) part of the issue reported in pyinstaller/pyinstaller#7452.
> hooks: prevent pyqtgraph hook from recursing into pyqtgraph.examples

- news/557.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cv2.py
Add logic for finding the `cv2` extension module in cases when user builds OpenCV from source or uses official OpenCV Windows installer package instead of PyPI wheels.
Closes #110.
Requires PyInstaller >= 5.3 to work correctly.
Requires pyinstaller/pyinstaller#7495 to properly exclude `cv2.load_config_py2`, although in the grand scheme of things, that's mostly a cosmetic thing. There is also an issue with the TOC class (surprise suprise) that we need to work around.
Tested on linux with manually built OpenCV and on Windows with OpenCV installed using Windows installer for the latest release.
Here's a [oneshot test](https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/4440968425) across different PyPI versions to ensure that nothing is (obviously) broken. On Linux, the …
> hooks: cv2: add support for OpenCV built by user from source

- news/559.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-moviepy.audio.fx.all.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-moviepy.video.fx.all.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
These hooks collect corresponding audio/video submodules (which are imported programmatically), which fixes the attribute-not-found error when importing `moviepy.editor` in the frozen application.
> hooks: add hooks for moviepy.audio.fx.all and moviepy.video.fx.all

- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
- README.md
- scripts/cloud-test.py
Custom flags are likely to be `-m slow` or `-k some_test`.
Also bump the default Python versions.
> Oneshot CI: Support appending custom pytest flags

- .github/workflows/pr-test.yml
- requirements-test-libraries.txt
Add steps that run slow tests for scikit-image and/or scikit-learn when the corresponding package versions are explicitly updated in `requirements-tests-libraries`.
> ci: conditionally enable slow tests for scikit-image and scikit-learn

- news/565.update.1.rst
- news/565.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.data.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.filters.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.morphology.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update scikit-image hooks for compatibility with 0.19.x and 0.20.0. The 0.19.x series introduced custom lazy module loader, which in our case affects `skimage.filters`. In 0.20.0, they switched to `lazy_loader`, which requires us to collect `__init__.pyi` files. In addition `skimage.morphology` introduced two mandatory .npy data files that it tries to load at import.
Supersedes and closes #565.
> hooks: update scikit-image hooks for compatibility with 0.19.x and 0.20.0

- news/570.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torch.py
With torch 2.0.0, we seem to hit the recursion limit just by importing the module. Therefore, if we detect torch >= 2.0.0, ensure that recursion limit is at least 5000 by raising it if necessary.
Hopefully this will reduce amount of issue reports like pyinstaller/pyinstaller#7537 as torch 2.0.0 becomes more widespread...
> hooks: torch: automatically increase recursion limit for torch >= 2.0.0

- news/575.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyshark.py
`pyshark` now uses `termcolor` instead of `py._io.terminalwriter` for writing colored text to terminals.
> Remove py hidden imports for pyshark >= 0.6.

- news/576.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py
This commit adds the missing email-validator package required by Pydantic when validating email.
Without it, we have to manually append the package `email_validator` on the hidden-import argument.
You can find more information about this change in the documentation at https://docs.pydantic.dev/latest/install/#optional-dependencies .
> Add email_validator to the list of pydantic optional dependencies hidden imports

- .github/workflows/pr-test.yml
- news/573.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pylsl.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This adds a hook for pylsl, i.e., the Python wrapper around labstreaminglayer,  which is also known as LSL.
The pylsl package loads the C++ liblsl library using CDLL. The logic for locating liblsl is replicated here; subsequently it is added to the binaries and packaged in the compiled version in `pylsl/lib` which ensures that  pylsl will be able to find it.
See also
-  https://labstreaminglayer.readthedocs.io
-  https://github.com/labstreaminglayer/pylsl
-  https://github.com/sccn/liblsl
I tested it successfully on macOS and Windows, using a few methods to install liblsl (using conda, using homebrew, and using a local copy and the PYLSL_LIB variable).
> Add hook for pylsl

- news/542.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-customtkinter.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This adds a hook for [customtkinter](https://pypi.org/project/customtkinter/)
> Add hook for customtkinter

- news/583.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-fastparquet.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Closes #580.
While I would have liked to use the `PyInstaller.utils.hooks.collect_delvewheel_libs_directory` helper for this, at the moment we impose no PyInstaller version limit on these hooks while we would need
- PyInstaller >= 5.6 to have the helper available in the first place
- PyInstaller >= 5.11 to have the helper collect the `.load_order` file
- PyInstaller >= 5.4 to prevent duplication of DLLs due to lack of parent path preservation in older PyInstaller versions.
So for now, we do this "the old way", like we do in other hooks in this repository (e.g., `av`, `shapely`).
> Add hook for fastparquet

- news/587.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sympy.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `sympy` that automatically raises recursion limit to 5000 if `sympy` >= 1.12 is detected.
Closes #584.
Oneshot: [before](https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/5050627060/jobs/9061568971) and [after](https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/5050708408) - as can be seen, we could get away without raising the limit under python 3.8, but let's tie this only to `sympy` version for now...
> hooks: add hook for sympy

- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Use `compliance_checker/tests/data/bad-trajectory.nc` as a test file; in contrast to previously used `trajectory.nc`, the `bad-trajectory.nc` is part of `compliance-checker`'s git repository, and is available in 5.1.0 wheel.
> tests: compliance_checker: use a different .nc file

- news/590.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-xyzservices.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Yet another dependency of `panel` breaking this week's update tests.
> Add hook for xyzservices

- news/594.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.color.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.draw.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.exposure.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.future.py
Add hooks for sub-packages that are now using `lazy_loader`; we need to collect the `__init__.pyi` and all submodules.
> hooks: update scikit-image hooks for compatibility with version 0.21.0

- requirements-test-libraries.txt
The latest release of `adbutils` (1.2.11) explicitly pins `requests<2.16`, resulting in installation of `requests-2.15.1`, which is incompatible with python >= 3.10 due to use of `collections.Mapping` that was moved to `collections.abc`.
Hence, the package is essentially incompatible with python >= 3.10, and we should not be testing it there.
> test requirements: restrict adbutils to python < 3.10

- news/596.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-googleapiclient.model.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
The hook `googleapiclient.model` was raising this warning when running Pyinstaller: `WARNING: collect_data_files - skipping data collection for module 'googleapiclient.discovery' as it is not a package.` Needing workarounds to run the api client, see https://github.com/googleapis/google-api-python-client/issues/876. But this can be fixed by pointing it to the correct package `googleapiclient.discovery_cache`.
The test also received an improvement. The current test only run `from googleapiclient.discovery import build` which is  not sufficient because the error happens when calling the `build` function. Calling this function doesn't require a valid API key.
[Github Actions](https://github.com/ArthurKlausHoff/pyinstaller-hooks-contrib/actions/runs/5246383593)
> hooks: Fix googleapiclient.model missing docs and improve test

- news/599.update.1.rst
- news/599.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cairocffi.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-netCDF4.py
Update hooks for `cairocffi` and `netCDF4` for their latest released versions.
> Fix weekly breakage

- news/611.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pydantic.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
The v2.0.0 of pydantic seems to have removed the `pydantic.compiled` attribute, and cython-compiled version of PyPI wheels do not seem to be available anymore.
Fixes #610.
> hooks: update pydantic hook for compatibility with pydantic v2.0.0

- news/614.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-jsonschema.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-jsonschema_specifications.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Required for jsonschema >= 4.18.0, where bundled specification files have been moved into separate package.
Fixes #613.
> hooks: add hook for jsonschema_specifications

- news/617.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-ens.py
Add hook for `ens` package to collect its data files. Required by `web3` >= 6.6.0.
> hooks: add hook for ens package

- news/621.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-graphql_query.py
Update `graphql_query` hook for compatibility with `graphql-query` v1.2.0. Collect data files from `graphql_query` instead of `graphql_query.templates`; the templates directory cannot be treated as a namespace subpackage anymore due to introduction of eponymous submodule.
> hooks: update graphql_query hook for compatibility with v1.2.0

- news/627.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-opencc.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [opencc-python](https://github.com/yichen0831/opencc-python).
Note: The name of the project and Github repository is `opencc-python`, which is a pure Python implementation of [OpenCC](https://github.com/yichen0831/opencc-python). The package name in PyPI is `opencc-python-reimplemented`. And the name used to import the package in Python is `opencc`.
> hooks: add hook for opencc-python

- news/628.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-jieba.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [jieba](https://github.com/fxsjy/jieba) which is a Chinese word tokenization library.
> hooks: add hook for jieba

- news/630.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-wordcloud.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [wordcloud](https://github.com/amueller/word_cloud), which is a word cloud generator.
> hooks: add hook for wordcloud

- news/631.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-eng_to_ipa.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [eng_to_ipa](https://github.com/mphilli/English-to-IPA), which is library for converting English text into the [International Phonetic Alphabet](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet).
> hooks: add hook for eng_to_ipa

- news/632.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-mecab.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [python-mecab-ko](https://github.com/jonghwanhyeon/python-mecab-ko), which is a python binding for [mecab-ko](https://bitbucket.org/eunjeon/mecab-ko).
> hooks: add hook for python-mecab-ko

- news/633.new.1.rst
- news/633.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-khmernltk.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pycrfsuite.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [khmer-nltk](https://github.com/VietHoang1512/khmer-nltk), which is a Khmer (Cambodian) natural language processing toolkit.
> hooks: add hook for khmer-nltk and python-crfsuite

- news/634.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pymorphy3.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [pymorphy3](https://github.com/no-plagiarism/pymorphy3), which is a fork of [pymorphy2](https://github.com/pymorphy2/pymorphy2), which then is a morphological analyzer for Russian and Ukrainian.
The Ukrainian model (`pymorphy3-dicts-uk`) is not installed automatically as a dependency of `pymorphy3`, so it needs to be handled separately.
Notes: The maintenance of the [pymorphy2](https://github.com/pymorphy2/pymorphy2) project has stalled (pymorphy2/pymorphy2#160), and [pymorphy3](https://github.com/no-plagiarism/pymorphy3) seems to be the most active fork available now (the [spaCy](https://spacy.io/) project widely used for multilingual NLP has already switched from `pymorphy2` to `pymorphy3` in explosion/spaCy#11345).
> hooks: add hook for pymorphy3

- news/635.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sudachipy.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [SudachiPy](https://github.com/WorksApplications/sudachi.rs/tree/develop/python), which is a Python binding of [Sudachi](https://github.com/WorksApplications/Sudachi), which then is a Japanese morphological analyzer.
There are 3 types of dictionary: `sudachidict-small`, `sudachidict-core`, `sudachidict-full`, all of which needs to be installed separately.
> hooks: add hook for SudachiPy

- news/636.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-enchant.py
Fix an issue with enchant 2 using a different directory (in MacPorts)
> Fix an issue with enchant hook

- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Modify the `pymorphy3` test to dynamically determine what dictionaries (`ru`, `uk`) are available in the environment, and test for that. Allows the test to run when the pyup pull request updates only the `morphy3` package (which installs only `ru` dictionary by default).
> tests: allow test_pymorphy3 to run without the uk dictionary installed

- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/tests/test_wx_lib_pubsub.py
The tests for `wx.lib.pubsub` should be in this repository, where the corresponding hook resides.
> tests: migrate tests for wx.lib.pubsub from the main repository

- news/644.new.1.rst
- news/644.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-laonlp.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pythainlp.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [LaoNLP](https://github.com/wannaphong/LaoNLP), which is an NLP library for Lao (Laotian).
Another hook for [PyThaiNLP](https://github.com/PyThaiNLP/pythainlp), which is an NLP library for the Thai language, is also added.
> hooks: add hooks for LaoNLP and PyThaiNLP

- news/646.update.rst
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_nltk.py
If `nltk_data` can be found both in the frozen program and under the default location specified by `NLTK`, the former should be preferred to the latter.
> hooks: update runtime hook for NLTK

- news/652.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.feature.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.measure.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.registration.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.restoration.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.transform.py
Add/modify hooks for skimage sub-packages that switched to lazy loader in scikit-image 0.22.0.
> hooks: update skimage hooks for scikit-image 0.22.0

- news/656.new.1.rst
- news/656.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-eth_typing.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-eth_utils.network.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
- Collect metadata for eth_typing.
- Collect data file for eth_utils.network.
> Hooks for eth_typing and eth_utils

- news/657.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-rtree.py
Starting with RTree 1.0.0, the PyPI wheel for linux puts the `libspatialindex` shared library into top-level `Rtree.libs` directory.
Also, explicitly gate the codepath for Anaconda-based package based on the `INSTALLER` metadata to better handle situations when PyPI wheel is installed in Anaconda python environment.
Fixes #654.
> hooks: update rtree hook for compatibility with RTree 1.1.0

- news/666.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torch.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
I've read #531 and found a new solution.
We know thousands of headers are included in the wheel of torch, which are provided for situations like libraries which would be compiled when being installed as they should use the same version of CUDA, because none of source codes of PyTorch is included. So those header files can be simply filtered to reduce file amount in the packed application (so it can be moved or copied easier)
I still encountered a problem, though. After modifying these, tests on Linux will fail:
<details>
<summary>Click to expand</summary>
```
----------------------------- Captured stdout call -----------------------------
------- Starting build. -------
------- Build finished, now running executable. -------
[6545]  RUNNING: …
```
> Discard header files (and static libraries on Windows) of `torch`

- news/669.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sspilib.raw.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `sspilib` that collects submodules of `sspilib.raw`, most of which are cythonized extensions.
See https://github.com/pyinstaller/pyinstaller/issues/8136 .
> hooks: add hook for sspilib

- news/672.new.1.rst
- news/672.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-eth_rlp.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-rlp.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hooks for `rlp` and `eth_rlp`; as of their respective latest releases, both of these packages now query their version from metadata.
Fixes the failing `web3` tests in https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/671.
> Add hooks for rlp and eth_rlp

- .github/workflows/pr-test.yml
- news/673.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-sudachipy.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
`sudachipy` test depends on availability of dictionary packages (`sudachidict_small`, `sudachidict_core`, and `sudachidict_full`), so skip the test if they are not available.
In practice, this means that we likely will not be running this test on the pyup-bot PRs, unless both `sudachipy` and dictionary packages get updated at the same time.
> tests: fix dependencies of sudachipy test

- news/674.new.1.rst
- news/674.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-freetype.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-z3c.rml.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `z3c.rml` that collects the required subset of Bitstream Vera TTF fonts from `reportlab` package (this is in contrast to the initial plan and the usual approach of collecting all fonts in `reportlab` hook - because `reportlab` can be used without its bundled fonts, and because DarkGarden font is GPL'd).
Closes https://github.com/pyinstaller/pyinstaller/issues/8135.
Add hook for `freetype` that collects the shared library that is bundled with `freetype-py` PyPI wheels. The upstream has a hook, but due to an oversight, it is currently defunct. The idea is to provide our copy while they decide on the fix (https://github.com/rougier/freetype-py/pull/180) and until they push an update.
> Add hooks for z3c.rml and freetype

- news/675.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.feature.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
- src/_pyinstaller_hooks_contrib/tests/test_scikit_image.py
- src/_pyinstaller_hooks_contrib/tests/test_scikit_learn.py
Have the hook for `skimage.feature` collect the `orb_descriptor_positions.txt` file, which is required by `skimage.feature.ORB`. Closes https://github.com/pyinstaller/pyinstaller/issues/8176.
Add a basic test for ORB detector and descriptor extractor.
This PR also extracts the tests for scikit-image and scikit-learn from `test_libraries.py` into separate test files, as a first step of planned refactoring of that huge test file into smaller files based on a specific package or thematically similar packages.
> hooks: skimage.feature: collect file with ORB descriptor positions

- src/_pyinstaller_hooks_contrib/hooks/__init__.py
- src/_pyinstaller_hooks_contrib/hooks/rthooks/__init__.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/__init__.py
The package's implementation of `get_hook_dirs` currently returns the following paths:
```
[
'[...]/_pyinstaller_hooks_contrib/hooks/stdhooks',
'[...]/_pyinstaller_hooks_contrib/hooks/stdhooks/__pycache__',
'[...]/_pyinstaller_hooks_contrib/hooks/rthooks',
'[...]/_pyinstaller_hooks_contrib/hooks/rthooks/__pycache__',
'[...]/_pyinstaller_hooks_contrib/hooks',
]
```
whereas only
```
[
'[...]/_pyinstaller_hooks_contrib/hooks/stdhooks',
'[...]/_pyinstaller_hooks_contrib/hooks',
]
```
would suffice. The first path is required because we use non-standard layout for standard hooks - normally, PyInstaller expects them to be in the top-level hooks directory. All other hooks are discovered based on the top-level hooks directory (the second path), including the run-time hooks; PyInstaller looks for …
> cleanup: clean up and simplify `get_hooks_dirs` entry-point

- news/679.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-vaderSentiment.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
This PR adds a hook for [VADER](https://github.com/cjhutto/vaderSentiment), which is a valence-aware dictionary-based sentiment analyzer for English.
> hooks: add hook for VADER

- news/681.new.1.rst
- news/681.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-langchain.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-seedir.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hooks for `langchain` and `seedir` to collect data files from these packages.
See:
https://github.com/orgs/pyinstaller/discussions/8197
and 
https://github.com/pyinstaller/pyinstaller/issues/8205
> Add hooks for langchain and seedir

- news/684.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-PyTaskbar.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for [PyTaskbar](https://pypi.org/project/PyTaskbarProgress)
> Add hook for PyTaskbar

- news/691.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pypylon.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Fix the `pypylon` hook for compatibility with PyInstaller >= 6.0. The `collect_data_files(..., include_py_files=True)` does not include binary extensions anymore, and PyInstaller 6.2 (pyinstaller/pyinstaller@ecc218c) fixed the module exclusion for relative imports; so the extensions that hook tries to exclude actually end up excluded without being collected via the alternative codepath.
Presumably that part of hook was needed on older PyInstaller versions, so keep it around, but disable it for PyInstaller >= 6.0.
Fixes #689.
> hooks: fix pypylon hook for PyInstaller 6.0 and later

- news/692.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-fairscale.py
- src/_pyinstaller_hooks_contrib/tests/test_deep_learning.py
Add hook for `fairscale` to collect its source .py files for torchscript/JIT.
Add a basic import test that demonstrates the need for that.
> hooks: add hook for fairscale

- news/693.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-osgeo.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Had issues trying to use GDAL (using the unofficial windows binaries), when loading a chart with EPSG coordinates.  This required the data/proj folder to be bundled as well.
> Improve osgeo hook

- news/703.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-falcon.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
> hooks: add hook for falcon

- news/708.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-IPython.py
Update exclude list for GUI frameworks with contemporary Qt bindings (`PySide2`, `PySide6`, and `PyQt6`).
> hooks: IPython: update exclude list for GUI frameworks

- news/710.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyqtgraph.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update `pyqtgraph` hook to use Qt bindings selection helper, which should help to automatically exclude extraneous Qt bindings, in order to prevent multiple Qt bindings from being collected. The change requires PyInstaller >= 6.5 (and should be no-op with earlier versions).
Remove the explicit excludes in `pyqtgraph` tests.
> hooks: update pyqtgraph hook to use Qt bindings selection helper

- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
The change for `sspilib` https://github.com/jborean93/sspilib/pull/13 has changed the ordering of the arguments now that `credential` was deemed to be mandatory. While this was a breaking change this was the only example I found using GitHub search that showed an instance where the change would break. This PR uses kwargs to ensure it will work with the old and new syntax during the transition.
> Fix up sspilib credential ordering

- news/712.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torch.py
Add support for MKL-enabled `torch` builds on Windows (e.g., the nightly `2.3.0.dev20240308+cpu` build). The `torch` hook now attempts to discover and collect DLLs from MKL and its dependencies (`mkl`, `tbb`, `intel-openmp`).
This should prevent frozen program from silently crashing due to missing MKL DLLs, which slip past PyInstaller's binary dependency analysis due to being dynamically loaded at run time.
Closes pyinstaller/pyinstaller#8348.
> hooks: torch: add support for MKL-enabled torch builds

- news/716.new.rst
- news/716.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cloudpickle.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-numba.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update `numba` hook to ensure that `numba.cloudpickle.cloudpickle_fast` is collected when using `numba` v0.59.0 or later.
Add hook for `cloudpickle` to ensure that `cloudpickle.cloudpickle_fast` is collected when using `cloudpickle` v3.0.0 or later.
In `cloudpickle` v3.0.0 (upstream or vendored version in `numba`), the `cloudpickle_fast` module became a compatibility shim for unpickling data that was pickled with earlier versions. However, it is not directly imported from the `cloudpickle` package anymore. Therefore, it ends up missing from the frozen application and results in error when trying to unpickle data. See pyinstaller/pyinstaller#8337.
> hooks: collect `cloudpickle_fast` from `numba.cloudpickle` and `cloudpickle`

- news/722.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-netCDF4.py
Use the `collect_delvewheel_libs_directory` helper to ensure that DLLs and load-order file (if present) are collected from `netCDF4.libs` directory.
While contemporary PyInstaller versions automatically pick up DLLs from that directory thanks to dynamic DLL search path tracking, that does not work with Anaconda python 3.8 and 3.9, where, due to defunct `os.add_dll_directory` function, `delvewheel` needs to load DLLs via the load-order file.
Closes pyinstaller/pyinstaller#8405.
> hooks: netCDF4: explicitly collect files from netCDF4.libs

- news/725.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-opentelemetry.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `opentelemetry` that collects all entry-points with `opentelemetry_` prefix.
Closes pyinstaller/pyinstaller#8413.
> hooks: add hook for opentelemetry

- news/726.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-pyproj.py
Use the `collect_delvewheel_libs_directory` helper to ensure that DLLs and load-order file (if present) are collected from `pyproj.libs` directory.
While contemporary PyInstaller versions automatically pick up DLLs from that directory thanks to dynamic DLL search path tracking, that does not work with Anaconda python 3.8 and 3.9, where, due to defunct `os.add_dll_directory` function, `delvewheel` needs to load DLLs via the load-order file.
Closes pyinstaller/pyinstaller#8415.
> hooks: pyproj: explicitly collect files from pyproj.libs

- news/724.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/rthooks.dat
- src/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_cryptography_openssl.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cryptography.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Have the `cryptography` hook collect OpenSSL >= 3.0.0 modules from `ossl-modules` directory, if available. Add a run-time hook that sets `OPENSSL_MODULES` environment variable to the bundled `ossl-modules` directory.
This is required for `cryptography` to work with recent OpenSSL versions, where legacy algorithms were put into separate legacy module. This module can be a separate shared library (e.g., on Linux in general, on Windows in msys2/MinGW, and on macOS in Homebrew), so we need to make sure we collect it.
Add a basic test for `cryptography`, since thus far we don't have any at all. It is mostly intended to ensure that the hook works at all. Testing that modules are properly collected and used is somewhat tricky, due to their conditional availability and due to the fact that if …
> hooks: cryptography: collect OpenSSL >= 3.0.0 modules, if available

- .github/workflows/lint.yml
- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
- .github/workflows/release.yml
- .github/workflows/validate-new-news.yml
Bump versions of used actions to silence warnings about deprecation of Node.js 16 actions.
> ci/cd: bump actions versions

- news/728.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-xarray.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `xarray`, which ensures that metadata for `numpy` (required by `xarray`) is collected.
Closes pyinstaller/pyinstaller#8392. Closes pyinstaller/pyinstaller#8417.
> hooks: add hook for xarray

- news/731.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-gcloud.py
Supress errors raised by `copy_metadata`; these may occur when the hook is triggered by the `gcloud` namespace package from `gcloud-aio-*` and `gcloud-rest-*` dists instead of the `gcloud` package from the `gcloud` dist.
Closes #730.
> hooks: gcloud: suppress errors

- news/732.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-tables.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Update hook for `tables` (PyTables) to collect blosc2 shared library that may be bundled with the package (PyPI wheels).
Also use the `collect_delvewheel_libs_directory` helper to ensure that DLLs and load-order file (if present) are collected from `tables.libs` directory (Windows PyPI wheels).
Closes pyinstaller/pyinstaller#8419.
> hooks: update tables hook to collect blosc2 shared library

- news/735.new.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-backports.py
Add hook for `backports` package, to accommodate the `pkgutil`-style `backports` namespace package provided by `backports.functools-lru-cache` and the latest release of `backports.tarfile`.
The `__init__.py` file from this `backports` namespace package uses `__import('pkgutil')__`, which slips past PyInstaller's modulegraph analysis, hence we need a hidden import.
This should fix the macOS test failures from yesterday's CI run in the main PyInstaller repository: https://github.com/pyinstaller/pyinstaller/actions/runs/8791000204/job/24124262352 
The culprit `keyring`, which imports `jaraco.context`, which (on python < 3.12) imports `backports.tarfile`, which added `pkgutil`-style namespace package in the recent 1.1.1 release
> hooks: add hook for backports namespace package

- news/742.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-schwifty.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `schwfity` that collects the data files (the JSON files in `bank_registry`) and package's metadata.
> hooks: add hook for schwifty

- .github/workflows/pr-test.yml
- news/744.new.rst
- news/744.update.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-gribapi.py
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-xarray.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Extend the `xarray` hook to collect additional backend plugins that are registered via the `xarray.backends` entry-point (e.g., `cfgrib`).
Add hook for `gribapi` package from `eccodes` dist, in order to collect bundled headers and ensure that the eccodes shared library is collected from the build environment.
Manually tested on Windows with Anaconda with program that tries to read a grib file. 
The `test_eccodes_gribapi` might pass on linux, but in reality, the collected shared library cannot yet be discovered (and so the system copy is used). For this to properly work, we will need to add an override for POSIX implementation of `ctypes.util.find_library` in PyInstaller's bootstrap/loader, which would explicitly search for matching filenames in `sys._MEIPASS`.
Closes #744.
> Improve support for cfgrib

- news/600.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dbus_fast.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Add hook for `dbus_fast` in order to collect submodules that are imported from cythonized extensions.
Closes #660.
> hooks: add hook for dbus_fast

- news/748.new.rst
- requirements-test-libraries.txt
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-patoolib.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
test run here: https://github.com/mtayeldev/pyinstaller-hooks-contrib/actions/runs/9180607046 (for some reason it fails for unrelated test cases)
original issue: https://github.com/pyinstaller/pyinstaller/issues/3013
> Add hook for patoolib

- setup.cfg
With pytest-dev/pytest#11233, enabling summaries for xfailed tests also enables their full error tracebacks, which complicates finding the actual test failures. There is no way of disabling just the tracebacks, so disable the summaries of xpassed/xfailed tests altogether.
> tests: disable summary of xpassed/xfailed tests

- news/760.update.rst
- src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-hydra.py
- src/_pyinstaller_hooks_contrib/tests/test_libraries.py
Under python < 3.10, `hydra`'s plugin manager continues to use deprecated PEP-302 functionality that was removed from PyInstaller's `PyiFrozenImporter` in PyInstaller 5.8 (pyinstaller/pyinstaller#7344.). At run-time, this results in `AttributeError: 'PyiFrozenImporter' object has no attribute 'find_module'`.
As a work-around, check python version and PyInstaller version, and if using python < 3.10 and PyInstaller >= 5.8, set module collection mode for `hydra._internal.core_plugins` and `hydra_plugins` packages to `py` to collect their modules as source .py files only. This way, they end up handled by python's built-in finder/importer, instead of PyInstaller's `PyiFrozenImporter`.
> hooks: hydra: add work-around for python < 3.10 and PyInstaller >= 5.8

- .github/workflows/release.yml
- news/761.process.rst
- src/_pyinstaller_hooks_contrib/__init__.py
* Create a release tag after generating the changelog so that `https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/refs/heads/$version.zip` and `https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/$version/CHANGELOG.rst` contain the right changelog entries
* Similarly, create sdists after generating the changelog so that they also contain the current release's changelog entries
* Bump the project version immediately before release rather than after (for convenience of implication rather than any functional reason)
* Rename GitHub releases from `XXXX.X` to `vXXXX.X` to match the tags. This in turn fixes GitHub generating additional tags without the `v` suffix
Verification [run](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/9946733033) and [mock …
> Fix release tag/version management

- _pyinstaller_hooks_contrib/stdhooks/hook-imageio_ffmpeg.py
- news/766.update.rst
Starting with `imageio-ffmpeg` 0.5.0, `imageio_ffmpeg.binaries` is a package that is acccessed via `importlib.resources`. Since it is not directly imported anywhere, we need to add it to hidden imports.
Closes https://github.com/pyinstaller/pyinstaller/issues/8664.
> hooks: update imageio_ffmpeg hook for compatibility with imageio-ffmpeg >= 0.5.0

- _pyinstaller_hooks_contrib/stdhooks/hook-cryptography.py
- news/768.update.rst
Instead of trying to infer OpenSSL version by looking at `CRYPTOGRAPHY_OPENSSL_300_OR_GREATER` attribute of `cryptography.hazmat.backends.openssl.backend._lib`, use `cryptography.hazmat.backends.openssl.backend.openssl_version_number()` to obtain full OpenSSL version number.
Fixes compatibility with `cryptography` 43.0.0, where the afore-mentioned attribute does not seem to be available anymore. `openssl_version_number()`, on the other hand, seems to be available in all versions going back to 2.8 (which is the first version that supports python 3.8).
Closes https://github.com/pyinstaller/pyinstaller/issues/8682
> hooks: cryptography: rework the OpenSSL version check

- _pyinstaller_hooks_contrib/stdhooks/hook-cmocean.py
- news/769.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Manually testing functionality worked perfectly fine, as well as the CI. However, I can't figure out how to make pytest work. It keeps failing with the warning:
```
WARNING: discover_hook_directories: Failed to process hook entry point 'EntryPoint(name='hook-dirs', value='_pyinstaller_hooks_contrib:get_hook_dirs', group='pyinstaller40')': AttributeError: module '_pyinstaller_hooks_contrib' has no attribute 'get_hook_dirs'
```
https://github.com/MattTheCuber/pyinstaller-hooks-contrib/actions/runs/10143643881/job/28045459292
> Add hook for cmocean

- _pyinstaller_hooks_contrib/stdhooks/hook-tzwhere.py
- news/772.new.rst
- tests/test_libraries.py
Add a hook for `tzwhere`, which has data files.
No change to `requirements-test-libraries.txt` per https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/771#issuecomment-2267146235
> Add hook for tzwhere (#771)

- _pyinstaller_hooks_contrib/stdhooks/hook-slixmpp.py
- news/784.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Fix runtime import error for [slixmpp](https://codeberg.org/poezio/slixmpp) Jabber library.
Modules in "features" are dynamically imported in the same way plugins are, however, unlike plugins imports, they are not detected automatically (probably due to the fact that import happens at runtime, when the client class is instantiated), leading to the following error:
```
Unable to load plugin: feature_starttls
Traceback (most recent call last):
File "slixmpp\plugins\base.py", line 78, in load_plugin
ModuleNotFoundError: No module named 'slixmpp.plugins.feature_starttls'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "slixmpp\plugins\base.py", line 82, in load_plugin
ModuleNotFoundError: No module named 'slixmpp.features'
Unable to …
```
> Add hook for slixmpp library

- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cublas.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cuda_cupti.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cuda_nvcc.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cuda_nvrtc.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cuda_runtime.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cudnn.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cufft.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.curand.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cusolver.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.cusparse.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.nccl.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.nvjitlink.py
- _pyinstaller_hooks_contrib/stdhooks/hook-nvidia.nvtx.py
- _pyinstaller_hooks_contrib/stdhooks/hook-tensorflow.py
- _pyinstaller_hooks_contrib/stdhooks/hook-ultralytics.py
- _pyinstaller_hooks_contrib/utils/nvidia_cuda.py
- news/786.new.rst
- news/786.update.1.rst
- news/786.update.rst
- tests/test_deep_learning.py
- tests/test_pytorch.py
- tests/test_tensorflow.py
Fix issues with run-time discovery of collected CUDA/cuDNN libraries on linux when using ``torch`` and/or ``tensorflow``.
Use the symlink suppression mechanism from https://github.com/pyinstaller/pyinstaller/pull/8761 to suppress creation of top-level directory symlinks for `libtensorflow_cc.so.2`, `libtensorflow_framework.so.2`, and  `_pywrap_tensorflow_internal.so` from `tensorflow` package. These symlinks cause `tensorflow` to mis-identify its location, and cause it to search for CUDA libraries in wrong directories. See https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/676#issuecomment-1866440960
For a very similar reason, suppress top-level directory symlink creation for all shared libraries from `nvidia.cu*` packages to fix `Unable to load any of …
> Fix issues with run-time discovery of collected CUDA/cuDNN libraries on linux

- _pyinstaller_hooks_contrib/rthooks/pyi_rth_tensorflow.py
Gracefully handle lack of `getsitepackages` in the `site` module. Fixes compatibility with early PyInstaller 5.x versions (< 5.4), and future-proofs the hook in case the `getsitepackages` function ever legitimately ends up being unavailable.
Closes #789. While I don't particularly care for compatibility with outdated PyInstaller versions (< 5.4 that are affected), the code in question already tries to handle the case when `_orig_getsitepackages` is `None`, so it makes sense to add that default value for `getattr`.
> rthooks: tensorflow: gracefully handle lack of getsitepackages in site

- _pyinstaller_hooks_contrib/stdhooks/hook-yapf_third_party.py
- news/792.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `yapf_third_party` (part of `yapf`) to collect its data files.
Closes #783.
> hooks: add hook for yapf_third_party

- _pyinstaller_hooks_contrib/stdhooks/hook-grapheme.py
- news/793.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `grapheme` to collect its data files.
See https://github.com/pyinstaller/pyinstaller/issues/8760.
> hooks: add hook for grapheme

- _pyinstaller_hooks_contrib/stdhooks/hook-av.py
- news/794.update.rst
- requirements-test-libraries.txt
With `av` 13.0.0, one of the cythonized modules (`av.audio.layout`) started using `dataclasses`. Add it to hidden imports to ensure it is collected in cases when it is not referenced from anywhere else.
> hooks: update av hook for compatibility with av 13.0.0

- .github/workflows/pr-test.yml
- _pyinstaller_hooks_contrib/stdhooks/hook-xarray.py
- news/800.update.rst
- tests/test_libraries.py
Have the `xarray` hook collect `xarray.chunkmanagers` entry-points; this ensures that at least the default (`dask`) chunk manager is detected as present at the run-time.
Closes https://github.com/pyinstaller/pyinstaller/issues/8786.
> hooks: xarray: collect xarray.chunkmanagers entry-points

- tests/test_trame.py
Have `test_trame.py` use the `is_module_satisfies` instead of `check_requirement`, due to latter being available only in PyInstaller >= 6.0.
Closes #801.
> tests: fix compatibility with PyInstaller 5.x

- _pyinstaller_hooks_contrib/stdhooks/hook-pydicom.py
- news/796.update.rst
- requirements-test-libraries.txt
Update the hidden imports for renamed and extended set of plugin modules, and collect the data files that are now required at run-time due to `pydicom.examples` being imported during `pydicom` module initialization.
Closes #795.
> hooks: update pydicom hook for compatibility with pydicom v3.0.0

- .github/workflows/pr-test.yml
- _pyinstaller_hooks_contrib/rthooks.dat
- _pyinstaller_hooks_contrib/rthooks/pyi_rth_findlibs.py
- _pyinstaller_hooks_contrib/stdhooks/hook-gribapi.py
- news/799.new.rst
- news/799.update.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Starting with `eccodes` v2.37.0, upstream provides binary wheels with bundled copy of the `eccodes` shared library. Adjust the hook for `gribapi` (part of `eccodes` dist) to account for that. Also handle the issue with circular imports by importing `eccodes` before `gribapi.bindings` when trying to obtain the path to the shared library.
> hooks: update gribapi hook for compatibility with eccodes v2.37.0

- _pyinstaller_hooks_contrib/stdhooks/hook-setuptools_scm.py
- news/805.new.rst
Add hook for `setuptools_scm` to ensure that metadata for `setuptools` dist is collected, in order to avoid the following run-time warning:
```
ERROR: setuptools==0.dev0+unknown is used in combination with setuptools_scm>=8.x
Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61
Suggested workaround if applicable:
- migrating from the deprecated setup_requires mechanism to pep517/518
and using a pyproject.toml to declare build dependencies
which are reliably pre-installed before running the build tools
```
> hooks: add hook for setuptools_scm

- _pyinstaller_hooks_contrib/stdhooks/hook-av.py
- news/814.update.rst
- requirements-test-libraries.txt
Add `uuid` (used by cythonized `av.opaque`) to ensure it is collected when not referenced from anywhere else.
> hooks: update av hook for compatibility with av 13.1.0

- .github/workflows/lint.yml
- .github/workflows/validate-new-news.yml
Use python from `actions/setup-python` for `lint` and `validate-new-news` workflows, as the latest version of system-provided python/pip guards against pip-installing packages into base system python environment.
> ci: use python from actions/setup-python

- _pyinstaller_hooks_contrib/stdhooks/hook-onnxruntime.py
- news/817.new.rst
- tests/test_deep_learning.py
Add hook for `onnxruntime` to ensure that provider plugins (located in `onnxruntime/capi` directory) are collected.
> hooks: add hook for onnxruntime

- _pyinstaller_hooks_contrib/stdhooks/hook-falcon.py
- news/820.update.rst
- requirements-test-libraries.txt
`falcon` v4.0.0 added couple of more cythonized modules that depend on `dataclasses`, `json`, and `wsgiref` modules from stdlib; so we need to add those to `hiddenimports`.
> hooks: update falcon hook for compatibility with falcon v4.0.0

- _pyinstaller_hooks_contrib/stdhooks/hook-numbers_parser.py
- news/823.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `numbers_parser` to ensure that the package's data file (`numbers_parser/data/empty.numbers`) is collected.
Closes #822.
> hooks: add hook for numbers_parser

- .github/workflows/pr-test.yml
Update the CI to cover all supported python versions. Switch from deprecated macos-12 runner to macos-13 (x86_64) and macos-14 (arm64).
> ci: add python 3.12 and 3.13, and use macos-13 and macos-14

- _pyinstaller_hooks_contrib/stdhooks/hook-torch.py
- news/834.update.rst
- tests/test_pytorch.py
On Linux, have the `torch` hook use the`bindepend_symlink_suppression` hook attribute to prevent PyInstaller's binary dependency analysis from creating symlinks to top-level application directory for shared libraries discovered in the `torch/lib` directory during binary dependency analysis.
These symbolic links confuse certain `torch` builds about the location of  `torch`, and prevent `torch/lib/libtorch_cuda_linalg.so` from being (dynamically) loaded. The problematic builds are wheels provided by https://download.pytorch.org/whl/torch for `torch` 1.13.x, 2.0.x, and 2.1.x (tested with 1.13.1+cu117, 2.0.1+cu117, and 2.1.2+cu118). Later versions do not seem to be affected. The wheels provided on PyPI do not seem to be affected either, regardless of the version.
However, these symlinks …
> hooks: torch: suppress generation of symlinks for shared libs

- _pyinstaller_hooks_contrib/stdhooks/hook-sklearn.tree.py
- news/838.update.rst
- requirements-test-libraries.txt
Update the `sklearn.tree` hook for compatibility with `scikit-learn` v1.6.0; we need to add `sklearn.tree._partitioner` to hidden imports.
> hooks: update sklearn.tree hook for compatibility with scikit-learn v1.6.0

- setup.cfg
- tests/test_deep_learning.py
- tests/test_libraries.py
- tests/test_scikit_image.py
- tests/test_scikit_learn.py
Disable pytest's `legacypath` plugin, and replace legacy `tmpdir` fixtures with `tmp_path`.
Use f-string formatting instead of `str.format()`.
> Minor test suite cleanup

- _pyinstaller_hooks_contrib/stdhooks/hook-ruamel.yaml.py
- news/844.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `ruamel.yaml` to collect its plugins, and ensure that plugins' `__plug_in__` modules are collected as source .py files (which is necessary for their discovery).
See pyinstaller/pyinstaller#8960.
> hooks: add hook for ruamel.yaml

- _pyinstaller_hooks_contrib/stdhooks/hook-cryptography.py
- news/846.update.rst
Revise the code for discovery and collection of the `ossl-modules` directory in the `cryptography` hook. We should be looking for this directory with OpenSSL plugins only if the OpenSSL bindings extension module in the `cryptography` package is dynamically linked against the OpenSSL shared library. Therefore, perform binary dependency analysis on the extension module, and use the obtained records to infer location of the OpenSSL shared library (if applicable).
PyPI wheels for `cryptography` have their bindings extension statically linked against OpenSSL, so we can avoid looking for the OpenSSL library and its corresponding `ossl-modules` directory altogether. This also reduces risk of collecting unrelated instance of the OpenSSL shared library that happens to be in search path. …
> hooks: cryptography: revise discovery and collection of the ossl-modules directory

- _pyinstaller_hooks_contrib/stdhooks/hook-sam2.py
- news/847.new.rst
- tests/test_deep_learning.py
Add hook for `sam2` (Segment Anything Model 2).
Requires pyinstaller/pyinstaller#8971 - otherwise the module-collection-mode setting for `enum` ends up being no-op.
Closes pyinstaller/pyinstaller#8966.
> hooks: add hook for sam2

- _pyinstaller_hooks_contrib/stdhooks/hook-triton.py
- news/848.update.rst
- tests/test_deep_learning.py
Update `triton` hook to collect backend-specific modules and data files from `triton.backends` sub-package that was introduced in triton v3.0.0.
Should close pyinstaller/pyinstaller#8968.
> hooks: update triton hook for compatibility with triton >= 3.0.0

- .github/workflows/pr-test.yml
- _pyinstaller_hooks_contrib/stdhooks/hook-pygraphviz.py
- news/849.update.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Rewrite `pygraphviz` hook to fix discovery and collection of `graphviz` files under various Linux distributions, in Anaconda environments (Windows, Linux, and macOS), and msys2 environments (Windows).
We now discover active `graphviz` installation on all OSes by looking for `dot` program in `PATH`. To find the location of shared libraries and the plugin directory on non-Windows, we now perform binary dependency analysis on the `dot` executable and look for known `graphviz` shared libraries in the results.
This improves the discovery on various platforms, and also fixes the issue where system-installed (on Linux) or Homebrew-installed (on macOS) `graphviz` shared libraries and plugins would end up being collected  instead of Anaconda-packaged ones when using Anaconda environment with …
> hooks: rewrite pygraphviz hook

- _pyinstaller_hooks_contrib/stdhooks/hook-prettytable.py
https://github.com/prettytable/prettytable/pull/321
> hooks: prettytable does not query its version from metadata after 3.12.0

- _pyinstaller_hooks_contrib/stdhooks/hook-dask.py
- news/852.update.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Update `dask` hook to collect template files from `dask/widgets/templates` directory; these file become mandatory when using `dask.array` and `jinja2` is available.
Add a basic import test for `dask.array`, and add `dask[array,diagnostics]` to `requirements-test-libaries.txt` (the `array` extra installs `numpy`, which is required for `dask.array`; the `diagnostics` extra installs `jinja2`, whose presence makes the template files mandatory).
> hooks: dask: collect template files from dask/widgets/templates

- .github/workflows/pr-test.yml
- _pyinstaller_hooks_contrib/stdhooks/hook-intake.py
- news/853.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for ``intake`` to ensure that package's data and binaries of the drivers plugin are collected.
> hooks: add hook for intake

- _pyinstaller_hooks_contrib/stdhooks/hook-fsspec.py
- news/856.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `fsspec` to ensure that package's metadata and submodules of the drivers plugin are collected.
> hooks: add hook for fsspec

- _pyinstaller_hooks_contrib/stdhooks/hook-numcodecs.py
- news/858.update.rst
- requirements-test-libraries.txt
Add a hidden import for `deprecated` module, which was added to one of cythonized extension in `numcodecs` v0.15.0.
Fixes pyinstaller/pyinstaller#8993.
> hooks: update numcodecs hook for compatibility with numcodecs v0.15.0

- _pyinstaller_hooks_contrib/stdhooks/hook-numba.py
- news/857.update.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hidden imports for dynamically redirected and loaded modules that were introduced as part of the new type system in upcoming `numba` v0.61.0.
Extend `numba` tests with a basic test that uses `numba.jit`, and a basic import test with `NUMBA_USE_LEGACY_TYPE_SYSTEM` set to 0.
Closes pyinstaller/pyinstaller#8989.
Oneshot run (0.60, 0.61rc1, 0.61rc2): https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/12828775609
> hooks: update `numba` hook for compatibility with upcoming v0.61

- _pyinstaller_hooks_contrib/stdhooks/hook-pypdfium2.py
- _pyinstaller_hooks_contrib/stdhooks/hook-pypdfium2_raw.py
- news/860.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hooks for `pypdfium2` (collect `version.json` file) and `pypdfium2_raw` (collect `version.json` file and bundled pdfium shared library).
> hooks: add hooks for pypdfium2 and pypdfium2_raw

- _pyinstaller_hooks_contrib/rthooks/pyi_rth_findlibs.py
- _pyinstaller_hooks_contrib/stdhooks/hook-gribapi.py
- news/865.update.rst
- requirements-test-libraries.txt
`findlibs` v0.1.0 broke compatibility with python < 3.10; due to incompatible typing annotation, attempting to import the package raises `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`.
Gracefully handle this situation by making this run-time hook no-op, in order to avoid crashing the frozen program even if it would never end up importing/using `findlibs` (which is the case with `gribapi` from `eccodes` when binary wheel with bundled shared libraries is used).
This one came up in today's pyup-bot update (https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/865).
In addition to adding work-around to run-time hook, also install `eccodes` on Windows and under python 3.13, since wheels for those are available now. Update the comments in the standard hook for …
> rthooks: findlibs: gracefully handle TypeError on findlibs import

- _pyinstaller_hooks_contrib/stdhooks/hook-tkinterdnd2.py
- news/868.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `tkinterdnd2` (>= 0.4.0) that collects shared library and .tcl files from platform-specific sub-directory under `tkinterdnd2/tkdnd`.
Closes #868.
> hooks: add hook for tkinterdnd2

- _pyinstaller_hooks_contrib/stdhooks/hook-rtree.py
- news/875.update.rst
- requirements-test-libraries.txt
In `rtree` 1.4.0, the top-level directory used to store shared libraries on Linux was renamed from `Rtree.libs` to `rtree.libs`. Have the hook check for both directories and use whichever is available.
> hooks: update rtree hook compatibility with rtree >= 1.4.0

- requirements-test-libraries.txt
- tests/test_libraries.py
In fsspec 2025.3.0, a new protocol entry was added to the registry without corresponding error message. This breaks our attempt to list working protocols, because fsspec's import handling code attempts to access non-existing `err` key, which results in a `KeyError` instead of `ImportError`. See https://github.com/fsspec/filesystem_spec/issues/1805.
Robustify the test by adding generic `Exception` handler in addition to the expected `ImportError` one.
Bump `fsspec` version to 2025.3.0.
> tests: add work-around for regression in fsspec 2025.3.0

- _pyinstaller_hooks_contrib/stdhooks/hook-distributed.py
- news/877.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hook for `distributed` package (i.e., `dask.distributed`) to collect its data files and modules from `distributed.http`.
> hooks: add hook for (dask) distributed

- _pyinstaller_hooks_contrib/stdhooks/hook-torch.py
- news/879.update.rst
Fix path matching for MKL DLLs in `torch` hook to work with either POSIX-style or Windows-style separators, as either can appear in the metadata's `RECORD` entries.
The `importlib_metadata.PackagePath.match()` does not seem to properly normalize the separator, so we now first resolve the file's location (which yields a `pathlib.Path`) and perform matching on resolved path.
Fixes #879.
> hooks: torch: fix path matching in MKL DLL collection part of the hook

- _pyinstaller_hooks_contrib/stdhooks/hook-dateutil.py
- news/881.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
This contains a data file dateutil-zoneinfo.tar.gz that we need to include for full functionality.
> hooks: add hook for python-dateutil

- _pyinstaller_hooks_contrib/rthooks/pyi_rth_pyqtgraph_multiprocess.py
- _pyinstaller_hooks_contrib/stdhooks/hook-h5py.py
- _pyinstaller_hooks_contrib/stdhooks/hook-pyproj.py
- news/873.update.1.rst
- news/873.update.2.rst
- news/886.update.rst
Assorted fixes from #873. The first two are in response to custom Debian repackaging. I don't understand the third – it looks like the `pyqtgraph` one should never have worked before.
[Oneshot](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/13981821570) + [pyqtgraph on Linux](https://github.com/bwoodsend/pyinstaller-hooks-contrib/actions/runs/13982044546) (needs xvfb)
> Debian fixes

- _pyinstaller_hooks_contrib/stdhooks/hook-niquests.py
- _pyinstaller_hooks_contrib/stdhooks/hook-urllib3.py
- _pyinstaller_hooks_contrib/stdhooks/hook-urllib3_future.py
- news/893.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hooks for `urllib3` and `urllib3_future` to handle indirect imports made by the `urllib3-future` implementation of the `urllib3` package and its own `urllib3_future` package. Remove the submodule collection from these two packages from `niquests` hook, as this should be now handled by the newly-added hooks.
> Add hooks for urllib3-future

- .github/workflows/lint.yml
- _pyinstaller_hooks_contrib/stdhooks/hook-bitsandbytes.py
- _pyinstaller_hooks_contrib/stdhooks/hook-gcloud.py
- _pyinstaller_hooks_contrib/stdhooks/hook-transformers.py
Replace occurrences of the "dot above" (U+02D9) character with the intended backtick character.
A counterpart of https://github.com/pyinstaller/pyinstaller/pull/9083.
> cleanup: replace occurrences of U+02D9 with backtick character

- _pyinstaller_hooks_contrib/stdhooks/hook-black.py
- _pyinstaller_hooks_contrib/stdhooks/hook-blib2to3.py
- _pyinstaller_hooks_contrib/stdhooks/hook-frictionless.py
- _pyinstaller_hooks_contrib/stdhooks/hook-pydantic.py
- news/897.new.1.rst
- news/897.new.rst
- news/897.update.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Add hooks for `black` / `blib2to3` and `frictionless`, and update `pydantic` hook to always collect package's submodules. Add a test for `pandera` (which does not need its own hook, but needs the other changes from this PR).
Based on https://github.com/orgs/pyinstaller/discussions/9073.
In the case of `black` and `blib2to3`, most of the hidden imports could actually be sorted out by analyzing .py files that are bundled together with the extensions (except for the pesky `<something>__mypyc`, which we find by going through the list of files in the dist's metadata). But for compatibility with existing PyInstaller versions, we do the classic `collect_submodules` approach.
> hooks: add hooks for black, blib2to3, frictionless

- _pyinstaller_hooks_contrib/stdhooks/hook-tkinterweb.py
- _pyinstaller_hooks_contrib/stdhooks/hook-tkinterweb_tkhtml.py
- news/899.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Hello!
I've been getting complaints about my package TkinterWeb not working with PyInstaller and thought I would add a hook now that the package is more mature.
I included hooks for both TkinterWeb and its child package TkinterWeb-Tkhtml but only included a test for Tkinterweb as it also tests TkinterWeb-Tkhtml indirectly. 
Hopefully this will suffice?
Thanks!
> Add TkinterWeb and TkinterWeb-Tkhtml hooks

- _pyinstaller_hooks_contrib/stdhooks/hook-pandas_flavor.py
- requirements-test-libraries.txt
- tests/test_libraries.py
Its lazy loader has been removed.
> Disable hiddenimports for pandas_flavor >= 0.7.0

- _pyinstaller_hooks_contrib/stdhooks/hook-narwhals.py
- news/908.update.rst
Have the `narwhals` hook check that `typing_extensions` is importable before trying to collect metadata for `typing_extensions` dist.
This fixes error when `typing-extensions` is unavailable (neither stand-alone dist is installed nor it is provided as part of `setuptools`), and also matches the behavior of `narwhals`, which tries to query the version via metadata only if `typing_extensions` is importable.
In addition, since `narwhals` queries metadata only on python < 3.13, skip the metadata collection when building with python 3.13 or later.
Fixes #907.
> hooks: fix narwhals hook when typing_extensions is unavailable

- _pyinstaller_hooks_contrib/rthooks/pyi_rth_usb.py
- news/913.update.rst
With this change, the ``find_library`` argument is now handled properly which fixed custom libusb file loading under pyinstaller. See issue #912 for details.
> Fixed issue #912 (USB find_library callback)

- _pyinstaller_hooks_contrib/stdhooks/hook-sklearn.externals.array_api_compat.cupy.py
- _pyinstaller_hooks_contrib/stdhooks/hook-sklearn.externals.array_api_compat.dask.array.py
- _pyinstaller_hooks_contrib/stdhooks/hook-sklearn.externals.array_api_compat.numpy.py
- _pyinstaller_hooks_contrib/stdhooks/hook-sklearn.externals.array_api_compat.torch.py
- news/915.new.rst
- requirements-test-libraries.txt
Add hooks for subpackages of `sklearn.externals.array_api_compat`:
- `sklearn.externals.array_api_compat.cupy`
- `sklearn.externals.array_api_compat.dask.array`
- `sklearn.externals.array_api_compat.numpy`
- `sklearn.externals.array_api_compat.torch`
These were introduced in `scikit-learn` v1.7.0 and require hidden imports due to the following programmatic imports:
```
__import__(__package__ + '.linalg')
__import__(__package__ + '.fft')
```
Fixes #914.
> hooks: add hooks for subpackages of sklearn.externals.array_api_compat

- _pyinstaller_hooks_contrib/stdhooks/hook-pynng.py
- news/922.new.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
On a PyInstaller application that had `pynng` as a dependency, this error was thrown when the executable started up:
```
File "PyInstaller/loader/pyimod02_importers.py", line 457, in exec_module
File "pynng/__init__.py", line 3, in <module>
ModuleNotFoundError: No module named '_cffi_backend'
```
`cffi` is a dependency of `pynng`:
https://github.com/codypiersall/pynng/blob/2179328f8a858bbb3e177f66ac132bde4a5aa859/pyproject.toml#L22
I based this PR off of a similar one for `bcrypt`
- https://github.com/pyinstaller/pyinstaller/pull/4750/
> Add hook for pynng

- .github/workflows/pr-test.yml
- _pyinstaller_hooks_contrib/stdhooks/hook-pylsl.py
- news/924.update.rst
- requirements-test-libraries.txt
- tests/test_libraries.py
Update `pylsl` hook for compatibility with `pylsl` >= 1.17.0. 
Have the corresponding test ensure that the bundled copy of shared library is used at run-time, to ensure that test fails if system-provided copy is used due to bundled copy either not being collected or not being loaded.
Install and test PyPI wheels for Windows, which come with bundled copy of `lsl` shared library.
> Update pylsl hook

- _pyinstaller_hooks_contrib/__init__.py
- news/928.update.rst
The recursion limit test in PyInstaller main repository seems to push the recursion level to the limit; and if the limit is set to 5000, this crashes python 3.8 - 3.10 on Windows and 3.9 that is (at the time of writing) available under Cygwin.
Further investigation revealed that Windows builds of python 3.8 and 3.10 handle recursion up to level ~2075, while the practical limit for 3.9 is between 1950 and 1975. Therefore, for affected combinations of platforms and python versions, use a conservative limit of 1900 - if only to avoid issues with the recursion limit test in the main PyInstaller repository...
For other platforms and python versions, leave the default limit at the 5000 as per earlier commit, although it is likely that it could be lowered as well.
> Adjust the automatically-raised recursion limit

- .github/workflows/oneshot-test.yml
- .github/workflows/pr-test.yml
Make use of installed `pytest-xdist` and run tests in parallel, by passing `-n logical` to `pytest`.
Use `-n logical` instead of `-n auto` because some of the runner VMs present their CPUs as logical cores rather than physical ones.
> ci: run tests in parallel

- _pyinstaller_hooks_contrib/stdhooks/hook-cumm.py
- _pyinstaller_hooks_contrib/stdhooks/hook-pointcept.py
- _pyinstaller_hooks_contrib/stdhooks/hook-torch.py
- news/941.new.1.rst
- news/941.new.rst
- news/941.update.rst
Fixes for issues that came up during pyinstaller/pyinstaller#9222:
1. extend MKL collection in `torch` hook to detect Anaconda-packaged `torch`, and collect DLLs from (Anaconda-packaged) `mkl` and its dependencies
2. add hook for `cumm` to collect header files from `cumm/include` directory
3. add hook for `pointcept` to collect source .py files for TorchScript.
Closes pyinstaller/pyinstaller#9222.
> Fixes for pyinstaller/pyinstaller#9222
